// Regional Markets Configuration for Crown Plastic Pipes - Phase 3 AEO
// Market-specific pages with LocalBusiness schema and regional targeting

export interface RegionalMarket {
  slug: string;
  country: string;
  countryCode: string;
  city?: string;
  cityAr?: string;
  countryAr: string;
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  keywords: string[];
  focus: string; // e.g., 'ISO compliance', 'commercial projects'
  focusAr: string;
  certifications: string[];
  cta: {
    text: string;
    textAr: string;
    link: string;
  };
  districts?: string[];
  geo?: {
    latitude: number;
    longitude: number;
  };
  telephone: string;
  deliveryTime: string;
  deliveryTimeAr: string;
  currency: string;
}

// ============================================
// SAUDI ARABIA MARKET PAGES
// ============================================

export const saudiMarkets: RegionalMarket[] = [
  {
    slug: 'saudi-arabia/upvc-pipes-iso-certified',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    countryAr: 'المملكة العربية السعودية',
    title: 'Export Ready & ISO Certified Pipes / Fittings for Saudi Arabia',
    titleAr: 'أنابيب / تجهيزات جاهزة للتصدير ومعتمدة ISO للسعودية',
    description: 'Crown Plastic offers ISO 9001:2015 certified Pipes / Fittings for the Saudi Arabian market. Manufactured to international quality standards (BS EN, DIN, ASTM). Bulk export to all Saudi cities.',
    descriptionAr: 'تقدم كراون بلاستيك أنابيب / تجهيزات معتمدة ISO 9001:2015 للسوق السعودي. مصنعة وفق المعايير الدولية (BS EN، DIN، ASTM). التصدير بالجملة لجميع المدن السعودية.',
    keywords: ['ISO certified UPVC pipes', 'Saudi Arabia pipe supplier', 'ASTM DIN compliant pipes', 'Saudi building materials', 'UPVC pipes KSA', 'BS EN 1452 pipes Saudi'],
    focus: 'International Quality Standards',
    focusAr: 'معايير الجودة الدولية',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785', 'DIN 8062'],
    cta: {
      text: 'Get ISO-Certified Pipes / Fittings',
      textAr: 'احصل على أنابيب / تجهيزات معتمدة ISO',
      link: '/contact-us?market=saudi-iso',
    },
    districts: ['Riyadh', 'Jeddah', 'Dammam', 'Mecca', 'Medina', 'Khobar', 'Jubail'],
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
    currency: 'AED',
  },
  {
    slug: 'saudi-arabia/riyadh-upvc-distributor',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Riyadh',
    cityAr: 'الرياض',
    countryAr: 'المملكة العربية السعودية',
    title: 'Pipes / Fittings Distributor in Riyadh, Saudi Arabia',
    titleAr: 'موزع أنابيب / تجهيزات في الرياض',
    description: 'Leading Pipes / Fittings distributor serving Riyadh and Central Region of Saudi Arabia. Fast delivery to Riyadh construction projects, competitive pricing, ISO certified products. Serving contractors, developers, and government projects.',
    descriptionAr: 'موزع أنابيب / تجهيزات رائد في خدمة الرياض والمنطقة الوسطى. توصيل سريع لمشاريع البناء في الرياض، أسعار تنافسية، منتجات معتمدة وفق معايير ISO.',
    keywords: ['UPVC pipes Riyadh', 'Riyadh pipe distributor', 'plastic pipes Riyadh', 'construction materials Riyadh', 'UPVC supplier Central Region'],
    focus: 'Riyadh delivery and pricing',
    focusAr: 'توصيل وأسعار الرياض',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: {
      text: 'Request Quote for Riyadh Delivery',
      textAr: 'اطلب عرض سعر للتوصيل إلى الرياض',
      link: '/contact-us?market=riyadh',
    },
    districts: ['Al Olaya', 'Al Malaz', 'Al Naseem', 'Al Sulay', 'Al Rawdah', 'Industrial City', 'King Abdullah Financial District'],
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
    currency: 'AED',
  },
  {
    slug: 'saudi-arabia/jeddah-upvc-wholesale',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Jeddah',
    cityAr: 'جدة',
    countryAr: 'المملكة العربية السعودية',
    title: 'Pipes / Fittings Wholesale Supplier in Jeddah',
    titleAr: 'مورد أنابيب / تجهيزات بالجملة في جدة',
    description: 'Wholesale Pipes / Fittings supplier for Jeddah and Western Region of Saudi Arabia. Container-load shipments, bulk pricing, port delivery to Jeddah Islamic Port. Serving large construction and infrastructure projects.',
    descriptionAr: 'مورد أنابيب / تجهيزات بالجملة لجدة والمنطقة الغربية. شحنات حاويات، أسعار بالجملة، توصيل لميناء جدة الإسلامي.',
    keywords: ['UPVC pipes wholesale Jeddah', 'Jeddah pipe supplier', 'bulk pipes Jeddah', 'construction materials Western Region', 'Jeddah Islamic Port delivery'],
    focus: 'Bulk orders and wholesale',
    focusAr: 'طلبات بالجملة وتجارة الجملة',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: {
      text: 'Bulk Order Form for Jeddah',
      textAr: 'نموذج طلب بالجملة لجدة',
      link: '/contact-us?market=jeddah-wholesale',
    },
    districts: ['Al Hamra', 'Al Rawdah', 'Al Safa', 'Industrial City', 'Jeddah Port Area', 'North Jeddah', 'South Jeddah'],
    geo: { latitude: 21.4858, longitude: 39.1925 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days via port',
    deliveryTimeAr: '٣-٥ أيام عمل عبر الميناء',
    currency: 'AED',
  },
];

// ============================================
// UAE MARKET PAGES (Additional to Phase 1)
// ============================================

export const uaeMarkets: RegionalMarket[] = [
  {
    slug: 'uae/upvc-pipes-dubai-commercial',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Dubai',
    cityAr: 'دبي',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings for Dubai Commercial Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع دبي التجارية',
    description: 'Premium Pipes / Fittings supplier for commercial construction projects in Dubai. Serving Dubai Marina, Downtown Dubai, Business Bay, DIFC, and major developments. Delivery, project consultation, bulk pricing.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لمشاريع البناء التجارية في دبي. خدمة دبي مارينا، داون تاون دبي، بزنس باي والمشاريع الكبرى.',
    keywords: ['UPVC pipes Dubai commercial', 'Dubai construction materials', 'Business Bay pipes', 'Downtown Dubai supplier', 'commercial plumbing Dubai'],
    focus: 'Commercial projects in Dubai',
    focusAr: 'المشاريع التجارية في دبي',
    certifications: ['BS EN 1452', 'DIN 8062', 'BS EN 805', 'Dubai Municipality Approved'],
    cta: {
      text: 'Commercial Project Inquiry',
      textAr: 'استفسار مشروع تجاري',
      link: '/contact-us?market=dubai-commercial',
    },
    districts: ['Dubai Marina', 'Downtown Dubai', 'Business Bay', 'DIFC', 'JLT', 'Dubai Hills', 'Meydan'],
    geo: { latitude: 25.2048, longitude: 55.2708 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
    currency: 'AED',
  },
  {
    slug: 'uae/upvc-pipes-abu-dhabi-government',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Abu Dhabi',
    cityAr: 'أبوظبي',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings for Abu Dhabi Government & Municipal Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع حكومة أبوظبي والبلدية',
    description: 'Certified Pipes / Fittings supplier for Abu Dhabi government, municipal, and infrastructure projects. ITC approved, Abu Dhabi Quality Mark eligible, extensive experience with ADNOC, Mubadala, and government contractors.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع حكومة أبوظبي والبلدية والبنية التحتية. معتمد من ITC، مؤهل لعلامة جودة أبوظبي.',
    keywords: ['Abu Dhabi government pipes', 'municipal projects Abu Dhabi', 'ITC approved pipes', 'Abu Dhabi infrastructure', 'ADNOC contractors'],
    focus: 'Government and municipal projects',
    focusAr: 'المشاريع الحكومية والبلدية',
    certifications: ['BS EN 1452', 'Abu Dhabi Quality Mark', 'ITC Approved', 'ISO 9001:2015'],
    cta: {
      text: 'Government Bidding Support',
      textAr: 'دعم العطاءات الحكومية',
      link: '/contact-us?market=abudhabi-government',
    },
    districts: ['Mussafah', 'KIZAD', 'Yas Island', 'Saadiyat', 'Al Reem Island', 'Khalifa City'],
    geo: { latitude: 24.4539, longitude: 54.3773 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 48 hours',
    deliveryTimeAr: 'نفس اليوم - ٤٨ ساعة',
    currency: 'AED',
  },
  {
    slug: 'uae/sharjah-industrial-supply',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Sharjah',
    cityAr: 'الشارقة',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes & Fittings for Sharjah Industrial & Manufacturing Projects',
    titleAr: 'أنابيب وتجهيزات لمشاريع الشارقة الصناعية والتصنيعية',
    description: 'Leading Pipes / Fittings supplier serving Sharjah\'s industrial hub. Supplying SAIF Zone, Hamriyah Free Zone, and Sharjah Industrial Area with BS EN and ASTM certified UPVC, PVC, PP-R, PEX & HDPE systems. Bulk supply for manufacturing facilities, warehouses, and industrial infrastructure.',
    descriptionAr: 'مورد رائد للأنابيب / التجهيزات يخدم المركز الصناعي في الشارقة. توريد لمنطقة صيف والمنطقة الحرة بالحمرية والمنطقة الصناعية بالشارقة بأنظمة UPVC و PVC و PP-R و PEX و HDPE المعتمدة وفق BS EN و ASTM.',
    keywords: ['pipes Sharjah industrial', 'SAIF Zone pipe supplier', 'Hamriyah Free Zone pipes', 'Sharjah manufacturing supply', 'industrial pipes UAE', 'UPVC fittings Sharjah'],
    focus: 'Industrial Hub & Manufacturing Supply',
    focusAr: 'المركز الصناعي والتوريد التصنيعي',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: {
      text: 'Industrial Supply Inquiry',
      textAr: 'استفسار التوريد الصناعي',
      link: '/contact-us?market=sharjah-industrial',
    },
    districts: ['SAIF Zone', 'Hamriyah Free Zone', 'Sharjah Industrial Area', 'Al Nahda', 'Al Majaz', 'University City', 'Muwaileh'],
    geo: { latitude: 25.3463, longitude: 55.4209 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
    currency: 'AED',
  },
  {
    slug: 'uae/ajman-residential-infrastructure',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ajman',
    cityAr: 'عجمان',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes & Fittings for Ajman Residential & Urban Development',
    titleAr: 'أنابيب وتجهيزات للتطوير السكني والحضري في عجمان',
    description: 'Certified Pipes / Fittings supplier for Ajman\'s growing residential and urban infrastructure projects. Serving Al Zorah, Ajman Uptown, Emirates City, and new township developments with complete UPVC, PVC, PP-R, PEX & HDPE plumbing and drainage systems.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع البنية التحتية السكنية والحضرية المتنامية في عجمان. خدمة الزوراء وأبتاون عجمان وإمارات سيتي ومشاريع التطوير الجديدة بأنظمة سباكة وصرف متكاملة.',
    keywords: ['pipes Ajman residential', 'Ajman plumbing supplier', 'urban infrastructure Ajman', 'Ajman construction materials', 'residential pipes UAE', 'UPVC fittings Ajman'],
    focus: 'Residential Development & Urban Infrastructure',
    focusAr: 'التطوير السكني والبنية التحتية الحضرية',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: {
      text: 'Ajman Project Quote',
      textAr: 'عرض سعر مشروع عجمان',
      link: '/contact-us?market=ajman-residential',
    },
    districts: ['Al Zorah', 'Ajman Uptown', 'Emirates City', 'Al Rashidiya', 'Al Nuaimia', 'Al Jurf Industrial', 'Ajman Corniche'],
    geo: { latitude: 25.4052, longitude: 55.5136 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
    currency: 'AED',
  },
  {
    slug: 'uae/umm-al-quwain-marine-industrial',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Umm Al Quwain',
    cityAr: 'أم القيوين',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes & Fittings for Umm Al Quwain Marine & Industrial Projects',
    titleAr: 'أنابيب وتجهيزات للمشاريع البحرية والصناعية في أم القيوين',
    description: 'Direct-from-factory Pipes / Fittings supply from our Umm Al Quwain manufacturing facility. Shortest lead times and factory-gate pricing for marine infrastructure, industrial projects, and coastal developments. Complete UPVC, PVC, PP-R, PEX & HDPE systems manufactured on-site to BS EN and ASTM standards.',
    descriptionAr: 'توريد أنابيب / تجهيزات مباشرة من مصنعنا في أم القيوين. أقصر أوقات تسليم وأسعار المصنع للبنية التحتية البحرية والمشاريع الصناعية والتطويرات الساحلية. أنظمة UPVC و PVC و PP-R و PEX و HDPE مصنعة في الموقع وفق معايير BS EN و ASTM.',
    keywords: ['pipes Umm Al Quwain', 'UAQ marine pipes', 'factory direct pipes UAE', 'industrial pipes UAQ', 'coastal infrastructure pipes', 'UPVC manufacturer UAQ'],
    focus: 'Marine & Industrial Applications (Factory HQ)',
    focusAr: 'التطبيقات البحرية والصناعية (مقر المصنع)',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: {
      text: 'Factory Direct Inquiry',
      textAr: 'استفسار مباشر من المصنع',
      link: '/contact-us?market=uaq-marine',
    },
    districts: ['UAQ Free Trade Zone', 'UAQ Marina', 'UAQ Industrial Area', 'Al Salamah', 'Old Town', 'Al Raas'],
    geo: { latitude: 25.5647, longitude: 55.5553 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - factory direct',
    deliveryTimeAr: 'نفس اليوم - مباشرة من المصنع',
    currency: 'AED',
  },
  {
    slug: 'uae/ras-al-khaimah-hospitality-industrial',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ras Al Khaimah',
    cityAr: 'رأس الخيمة',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes & Fittings for Ras Al Khaimah Hospitality & Industrial Zones',
    titleAr: 'أنابيب وتجهيزات لمناطق الضيافة والصناعة في رأس الخيمة',
    description: 'Premium Pipes / Fittings supplier for Ras Al Khaimah\'s hospitality, tourism, and industrial zone projects. Serving Al Marjan Island resorts, RAK Economic Zone, and Al Hamra developments with certified UPVC, PVC, PP-R, PEX & HDPE systems for hotels, resorts, and industrial facilities.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لمشاريع الضيافة والسياحة والمناطق الصناعية في رأس الخيمة. خدمة منتجعات جزيرة المرجان والمنطقة الاقتصادية ومشاريع الحمراء بأنظمة معتمدة للفنادق والمنتجعات والمنشآت الصناعية.',
    keywords: ['pipes Ras Al Khaimah', 'RAK hospitality pipes', 'Al Marjan Island plumbing', 'RAK Economic Zone pipes', 'hotel plumbing RAK', 'industrial pipes Ras Al Khaimah'],
    focus: 'Hospitality, Tourism & Industrial Zones',
    focusAr: 'الضيافة والسياحة والمناطق الصناعية',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: {
      text: 'RAK Project Inquiry',
      textAr: 'استفسار مشروع رأس الخيمة',
      link: '/contact-us?market=rak-hospitality',
    },
    districts: ['Al Marjan Island', 'RAK Economic Zone', 'Al Hamra Village', 'Al Nakheel', 'Jebel Jais Area', 'RAK Free Trade Zone', 'Khuzam'],
    geo: { latitude: 25.7895, longitude: 55.9432 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
    currency: 'AED',
  },
  {
    slug: 'uae/fujairah-oil-gas-marine',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Fujairah',
    cityAr: 'الفجيرة',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes & Fittings for Fujairah Oil & Gas, Marine & Desalination',
    titleAr: 'أنابيب وتجهيزات لمشاريع النفط والغاز والبحرية وتحلية المياه في الفجيرة',
    description: 'Specialized Pipes / Fittings supplier for Fujairah\'s oil & gas, marine, and desalination sectors. Serving FOIZ, Fujairah Port, and coastal industrial projects with chemically resistant UPVC, PVC, PP-R, PEX & HDPE systems built for harsh marine and industrial environments.',
    descriptionAr: 'مورد متخصص في الأنابيب / التجهيزات لقطاعات النفط والغاز والبحرية وتحلية المياه في الفجيرة. خدمة المنطقة الصناعية وميناء الفجيرة والمشاريع الساحلية بأنظمة مقاومة كيميائياً مصممة للبيئات البحرية والصناعية القاسية.',
    keywords: ['pipes Fujairah oil gas', 'Fujairah marine pipes', 'desalination pipes UAE', 'FOIZ pipe supplier', 'Fujairah Port infrastructure', 'chemical resistant pipes Fujairah'],
    focus: 'Oil & Gas, Marine & Desalination Projects',
    focusAr: 'النفط والغاز والمشاريع البحرية وتحلية المياه',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: {
      text: 'Fujairah Industrial Inquiry',
      textAr: 'استفسار صناعي الفجيرة',
      link: '/contact-us?market=fujairah-industrial',
    },
    districts: ['FOIZ', 'Fujairah Port', 'Dibba Al Fujairah', 'Al Faseel', 'Merashid', 'Sakamkam'],
    geo: { latitude: 25.1288, longitude: 56.3264 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
    currency: 'AED',
  },
];

// ============================================
// OTHER GCC MARKET PAGES
// ============================================

export const gccMarkets: RegionalMarket[] = [
  {
    slug: 'kuwait/upvc-pipes-supplier',
    country: 'Kuwait',
    countryCode: 'KW',
    city: 'Kuwait City',
    cityAr: 'مدينة الكويت',
    countryAr: 'الكويت',
    title: 'Pipes / Fittings Supplier for Kuwait',
    titleAr: 'مورد أنابيب / تجهيزات للكويت',
    description: 'ISO certified Pipes / Fittings exporter for Kuwait construction and infrastructure projects. Container shipments to Shuwaikh Port, competitive bulk pricing, full documentation for Kuwaiti customs clearance.',
    descriptionAr: 'مصدر أنابيب / تجهيزات معتمد وفق معايير ISO لمشاريع البناء والبنية التحتية في الكويت. شحنات حاويات إلى ميناء الشويخ.',
    keywords: ['UPVC pipes Kuwait', 'Kuwait pipe supplier', 'ISO certified Kuwait', 'Shuwaikh Port delivery', 'Kuwait construction materials'],
    focus: 'Kuwait market export',
    focusAr: 'تصدير لسوق الكويت',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'ISO 9001:2015'],
    cta: {
      text: 'Request Kuwait Export Quote',
      textAr: 'اطلب عرض سعر تصدير للكويت',
      link: '/contact-us?market=kuwait',
    },
    districts: ['Kuwait City', 'Hawalli', 'Farwaniya', 'Ahmadi', 'Jahra', 'Salmiya'],
    geo: { latitude: 29.3759, longitude: 47.9774 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
    currency: 'AED',
  },
  {
    slug: 'qatar/upvc-pipes-doha',
    country: 'Qatar',
    countryCode: 'QA',
    city: 'Doha',
    cityAr: 'الدوحة',
    countryAr: 'قطر',
    title: 'Pipes / Fittings for Qatar Construction Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع البناء في قطر',
    description: 'Premium Pipes / Fittings supplier for Qatar. Serving Doha, Lusail, The Pearl, and major infrastructure projects. Experience with World Cup legacy developments. QCS compliant products with full technical support.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لقطر. خدمة الدوحة ولوسيل واللؤلؤة ومشاريع البنية التحتية الكبرى.',
    keywords: ['UPVC pipes Qatar', 'Doha pipe supplier', 'Lusail construction', 'Qatar World Cup projects', 'QCS compliant pipes'],
    focus: 'Qatar infrastructure projects',
    focusAr: 'مشاريع البنية التحتية في قطر',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'QCS Compliant'],
    cta: {
      text: 'Qatar Project Inquiry',
      textAr: 'استفسار مشروع قطر',
      link: '/contact-us?market=qatar',
    },
    districts: ['Doha', 'Lusail', 'The Pearl', 'West Bay', 'Al Wakra', 'Industrial Area'],
    geo: { latitude: 25.2854, longitude: 51.5310 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
    currency: 'AED',
  },
  {
    slug: 'bahrain/upvc-pipes-manama',
    country: 'Bahrain',
    countryCode: 'BH',
    city: 'Manama',
    cityAr: 'المنامة',
    countryAr: 'البحرين',
    title: 'Pipes / Fittings Supplier for Bahrain',
    titleAr: 'مورد أنابيب / تجهيزات للبحرين',
    description: 'Pipes / Fittings supplier for Bahrain construction industry. Quick delivery via King Fahd Causeway or Khalifa Bin Salman Port. Serving Manama, Muharraq, and industrial areas. ISO certified products.',
    descriptionAr: 'مورد أنابيب / تجهيزات لصناعة البناء في البحرين. توصيل سريع عبر جسر الملك فهد أو ميناء خليفة بن سلمان.',
    keywords: ['UPVC pipes Bahrain', 'Manama pipe supplier', 'Bahrain construction materials', 'King Fahd Causeway delivery'],
    focus: 'Bahrain market',
    focusAr: 'سوق البحرين',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'ISO 9001:2015'],
    cta: {
      text: 'Bahrain Delivery Quote',
      textAr: 'عرض سعر توصيل البحرين',
      link: '/contact-us?market=bahrain',
    },
    districts: ['Manama', 'Muharraq', 'Riffa', 'Hamad Town', 'Isa Town', 'Sitra'],
    geo: { latitude: 26.2285, longitude: 50.5860 },
    telephone: '+971 6 543 6781',
    deliveryTime: '2-4 business days',
    deliveryTimeAr: '٢-٤ أيام عمل',
    currency: 'AED',
  },
  {
    slug: 'oman/upvc-pipes-muscat',
    country: 'Oman',
    countryCode: 'OM',
    city: 'Muscat',
    cityAr: 'مسقط',
    countryAr: 'عُمان',
    title: 'Pipes / Fittings for Oman Construction Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع البناء في عُمان',
    description: 'Pipes / Fittings exporter for Oman construction and infrastructure. Serving Muscat, Sohar, Salalah, and all Omani governorates. Delivery to Sultan Qaboos Port. ISO certified and international standards compliant.',
    descriptionAr: 'مصدر أنابيب / تجهيزات للبناء والبنية التحتية في عُمان. خدمة مسقط وصحار وصلالة وجميع المحافظات العمانية.',
    keywords: ['UPVC pipes Oman', 'Muscat pipe supplier', 'Oman construction materials', 'Sultan Qaboos Port delivery', 'Sohar industrial'],
    focus: 'Oman market',
    focusAr: 'سوق عُمان',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'ISO 9001:2015'],
    cta: {
      text: 'Oman Export Inquiry',
      textAr: 'استفسار تصدير عُمان',
      link: '/contact-us?market=oman',
    },
    districts: ['Muscat', 'Sohar', 'Salalah', 'Nizwa', 'Sur', 'Duqm'],
    geo: { latitude: 23.5880, longitude: 58.3829 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
    currency: 'AED',
  },
];

// ============================================
// CLEAN-SLUG MARKET ENTRIES (for Navbar links)
// These use simple geographic slugs to match the Navbar hrefs
// and are registered in generateStaticParams() via allRegionalMarkets
// ============================================

export const cleanSlugMarkets: RegionalMarket[] = [
  // Saudi Arabia — overview
  {
    slug: 'saudi-arabia/overview',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    countryAr: 'المملكة العربية السعودية',
    title: 'Pipes / Fittings Supplier for Saudi Arabia | Crown Plastic',
    titleAr: 'مورد أنابيب / تجهيزات للمملكة العربية السعودية | كراون بلاستيك',
    description: 'Crown Plastic supplies ISO 9001:2015 certified UPVC, PVC, PP-R, PEX & HDPE Pipes / Fittings to Saudi Arabia. Bulk export to all Saudi cities with competitive pricing.',
    descriptionAr: 'تورد كراون بلاستيك أنابيب / تجهيزات UPVC وPVC وPP-R وPEX وHDPE المعتمدة وفق ISO 9001:2015 للمملكة العربية السعودية. تصدير بالجملة لجميع المدن السعودية.',
    keywords: ['pipes Saudi Arabia', 'UPVC pipes KSA', 'Saudi Arabia pipe supplier', 'ISO certified pipes Saudi'],
    focus: 'Saudi Arabia nationwide supply',
    focusAr: 'التوريد على مستوى المملكة العربية السعودية',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785', 'DIN 8062'],
    cta: { text: 'Get a Saudi Arabia Quote', textAr: 'احصل على عرض سعر للسعودية', link: '/contact-us?market=saudi-arabia' },
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
    currency: 'AED',
  },
  // Saudi Arabia — Riyadh
  {
    slug: 'saudi-arabia/riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Riyadh',
    cityAr: 'الرياض',
    countryAr: 'المملكة العربية السعودية',
    title: 'Pipes / Fittings Supplier in Riyadh, Saudi Arabia',
    titleAr: 'مورد أنابيب / تجهيزات في الرياض، المملكة العربية السعودية',
    description: 'Leading Pipes / Fittings supplier serving Riyadh and the Central Region of Saudi Arabia. Fast delivery, competitive pricing, ISO certified products for construction projects.',
    descriptionAr: 'مورد رائد للأنابيب / التجهيزات في الرياض والمنطقة الوسطى. توصيل سريع، أسعار تنافسية، منتجات معتمدة وفق ISO لمشاريع البناء.',
    keywords: ['UPVC pipes Riyadh', 'Riyadh pipe supplier', 'plastic pipes Riyadh', 'construction materials Riyadh'],
    focus: 'Riyadh delivery and pricing',
    focusAr: 'توصيل وأسعار الرياض',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: { text: 'Request Riyadh Quote', textAr: 'اطلب عرض سعر لمنطقة الرياض', link: '/contact-us?market=riyadh' },
    districts: ['Al Olaya', 'Al Malaz', 'Industrial City', 'King Abdullah Financial District'],
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
    currency: 'AED',
  },
  // Saudi Arabia — Jeddah
  {
    slug: 'saudi-arabia/jeddah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Jeddah',
    cityAr: 'جدة',
    countryAr: 'المملكة العربية السعودية',
    title: 'Pipes / Fittings Supplier in Jeddah, Saudi Arabia',
    titleAr: 'مورد أنابيب / تجهيزات في جدة، المملكة العربية السعودية',
    description: 'Wholesale Pipes / Fittings supplier for Jeddah and Western Region. Container-load shipments, bulk pricing, port delivery to Jeddah Islamic Port.',
    descriptionAr: 'مورد أنابيب / تجهيزات بالجملة لجدة والمنطقة الغربية. شحنات حاويات، أسعار بالجملة، توصيل لميناء جدة الإسلامي.',
    keywords: ['UPVC pipes Jeddah', 'Jeddah pipe supplier', 'bulk pipes Jeddah', 'Jeddah Islamic Port delivery'],
    focus: 'Bulk orders and wholesale',
    focusAr: 'طلبات بالجملة وتجارة الجملة',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: { text: 'Bulk Order for Jeddah', textAr: 'طلب بالجملة لجدة', link: '/contact-us?market=jeddah' },
    districts: ['Al Hamra', 'Industrial City', 'Jeddah Port Area', 'North Jeddah'],
    geo: { latitude: 21.4858, longitude: 39.1925 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days via port',
    deliveryTimeAr: '٣-٥ أيام عمل عبر الميناء',
    currency: 'AED',
  },
  // UAE — Dubai
  {
    slug: 'uae/dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Dubai',
    cityAr: 'دبي',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings Supplier in Dubai, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في دبي، الإمارات',
    description: 'Premium Pipes / Fittings supplier for Dubai commercial and residential projects. Serving Dubai Marina, Downtown Dubai, Business Bay, DIFC with same-day delivery.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لمشاريع دبي التجارية والسكنية. خدمة دبي مارينا وداون تاون دبي وبزنس باي وDIFC مع التوصيل في نفس اليوم.',
    keywords: ['UPVC pipes Dubai', 'Dubai pipe supplier', 'construction materials Dubai', 'plumbing supplier Dubai'],
    focus: 'Commercial and residential projects in Dubai',
    focusAr: 'المشاريع التجارية والسكنية في دبي',
    certifications: ['BS EN 1452', 'DIN 8062', 'Dubai Municipality Approved', 'ISO 9001:2015'],
    cta: { text: 'Dubai Project Inquiry', textAr: 'استفسار مشروع دبي', link: '/contact-us?market=dubai' },
    districts: ['Dubai Marina', 'Downtown Dubai', 'Business Bay', 'DIFC', 'JLT', 'Dubai Hills'],
    geo: { latitude: 25.2048, longitude: 55.2708 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
    currency: 'AED',
  },
  // UAE — Abu Dhabi
  {
    slug: 'uae/abu-dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Abu Dhabi',
    cityAr: 'أبوظبي',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings Supplier in Abu Dhabi, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في أبوظبي، الإمارات',
    description: 'Certified Pipes / Fittings supplier for Abu Dhabi government, municipal, and infrastructure projects. ITC approved, Abu Dhabi Quality Mark eligible.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع حكومة أبوظبي والبلدية والبنية التحتية. معتمد من ITC.',
    keywords: ['pipes Abu Dhabi', 'Abu Dhabi pipe supplier', 'municipal projects Abu Dhabi', 'ITC approved pipes'],
    focus: 'Government and municipal projects in Abu Dhabi',
    focusAr: 'المشاريع الحكومية والبلدية في أبوظبي',
    certifications: ['BS EN 1452', 'Abu Dhabi Quality Mark', 'ITC Approved', 'ISO 9001:2015'],
    cta: { text: 'Abu Dhabi Project Inquiry', textAr: 'استفسار مشروع أبوظبي', link: '/contact-us?market=abu-dhabi' },
    districts: ['Mussafah', 'KIZAD', 'Yas Island', 'Saadiyat', 'Al Reem Island', 'Khalifa City'],
    geo: { latitude: 24.4539, longitude: 54.3773 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 48 hours',
    deliveryTimeAr: 'نفس اليوم - ٤٨ ساعة',
    currency: 'AED',
  },
  // UAE — Sharjah
  {
    slug: 'uae/sharjah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Sharjah',
    cityAr: 'الشارقة',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings Supplier in Sharjah, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في الشارقة، الإمارات',
    description: 'Pipes / Fittings supplier serving Sharjah industrial hub. Supplying SAIF Zone, Hamriyah Free Zone, and Sharjah Industrial Area with certified UPVC, PVC, PP-R, PEX & HDPE systems.',
    descriptionAr: 'مورد أنابيب / تجهيزات للمركز الصناعي في الشارقة. توريد لمنطقة صيف والمنطقة الحرة بالحمرية والمنطقة الصناعية.',
    keywords: ['pipes Sharjah', 'SAIF Zone pipe supplier', 'Hamriyah Free Zone pipes', 'Sharjah industrial supply'],
    focus: 'Industrial Hub & Manufacturing Supply',
    focusAr: 'المركز الصناعي والتوريد التصنيعي',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: { text: 'Sharjah Supply Inquiry', textAr: 'استفسار التوريد بالشارقة', link: '/contact-us?market=sharjah' },
    districts: ['SAIF Zone', 'Hamriyah Free Zone', 'Sharjah Industrial Area', 'Al Nahda'],
    geo: { latitude: 25.3463, longitude: 55.4209 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
    currency: 'AED',
  },
  // UAE — Ajman
  {
    slug: 'uae/ajman',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ajman',
    cityAr: 'عجمان',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings Supplier in Ajman, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في عجمان، الإمارات',
    description: 'Certified Pipes / Fittings supplier for Ajman residential and urban infrastructure projects. Serving Al Zorah, Ajman Uptown, and new developments.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع البنية التحتية السكنية والحضرية في عجمان. خدمة الزوراء وأبتاون عجمان والتطويرات الجديدة.',
    keywords: ['pipes Ajman', 'Ajman plumbing supplier', 'residential pipes Ajman', 'construction materials Ajman'],
    focus: 'Residential Development & Urban Infrastructure',
    focusAr: 'التطوير السكني والبنية التحتية الحضرية',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Ajman Project Quote', textAr: 'عرض سعر مشروع عجمان', link: '/contact-us?market=ajman' },
    districts: ['Al Zorah', 'Ajman Uptown', 'Emirates City', 'Al Rashidiya', 'Al Nuaimia'],
    geo: { latitude: 25.4052, longitude: 55.5136 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
    currency: 'AED',
  },
  // UAE — Umm Al Quwain
  {
    slug: 'uae/umm-al-quwain',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Umm Al Quwain',
    cityAr: 'أم القيوين',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings — Direct from Factory in Umm Al Quwain, UAE',
    titleAr: 'أنابيب / تجهيزات مباشرة من المصنع في أم القيوين، الإمارات',
    description: 'Direct-from-factory Pipes / Fittings supply from our Umm Al Quwain manufacturing facility. Shortest lead times and factory-gate pricing for marine, industrial, and coastal projects.',
    descriptionAr: 'توريد أنابيب / تجهيزات مباشرة من مصنعنا في أم القيوين. أقصر أوقات تسليم وأسعار المصنع للمشاريع البحرية والصناعية والساحلية.',
    keywords: ['pipes Umm Al Quwain', 'UAQ factory direct pipes', 'industrial pipes UAQ', 'marine pipes UAE'],
    focus: 'Marine & Industrial (Factory HQ)',
    focusAr: 'التطبيقات البحرية والصناعية (مقر المصنع)',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: { text: 'Factory Direct Inquiry', textAr: 'استفسار مباشر من المصنع', link: '/contact-us?market=uaq' },
    districts: ['UAQ Free Trade Zone', 'UAQ Marina', 'UAQ Industrial Area'],
    geo: { latitude: 25.5647, longitude: 55.5553 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - factory direct',
    deliveryTimeAr: 'نفس اليوم - مباشرة من المصنع',
    currency: 'AED',
  },
  // UAE — Ras Al Khaimah
  {
    slug: 'uae/ras-al-khaimah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ras Al Khaimah',
    cityAr: 'رأس الخيمة',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings Supplier in Ras Al Khaimah, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في رأس الخيمة، الإمارات',
    description: 'Pipes / Fittings supplier for Ras Al Khaimah hospitality, tourism, and industrial zone projects. Serving Al Marjan Island, RAK Economic Zone, and Al Hamra developments.',
    descriptionAr: 'مورد أنابيب / تجهيزات لمشاريع الضيافة والسياحة والمناطق الصناعية في رأس الخيمة. خدمة جزيرة المرجان والمنطقة الاقتصادية ومشاريع الحمراء.',
    keywords: ['pipes Ras Al Khaimah', 'RAK pipe supplier', 'Al Marjan Island plumbing', 'RAK Economic Zone pipes'],
    focus: 'Hospitality, Tourism & Industrial Zones',
    focusAr: 'الضيافة والسياحة والمناطق الصناعية',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'RAK Project Inquiry', textAr: 'استفسار مشروع رأس الخيمة', link: '/contact-us?market=rak' },
    districts: ['Al Marjan Island', 'RAK Economic Zone', 'Al Hamra Village', 'RAK Free Trade Zone'],
    geo: { latitude: 25.7895, longitude: 55.9432 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
    currency: 'AED',
  },
  // UAE — Fujairah
  {
    slug: 'uae/fujairah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Fujairah',
    cityAr: 'الفجيرة',
    countryAr: 'الإمارات العربية المتحدة',
    title: 'Pipes / Fittings Supplier in Fujairah, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في الفجيرة، الإمارات',
    description: 'Specialized Pipes / Fittings supplier for Fujairah oil & gas, marine, and desalination sectors. Serving FOIZ, Fujairah Port with chemically resistant UPVC, PVC, PP-R, PEX & HDPE systems.',
    descriptionAr: 'مورد متخصص في أنابيب / تجهيزات لقطاعات النفط والغاز والبحرية وتحلية المياه في الفجيرة. خدمة المنطقة الصناعية وميناء الفجيرة بأنظمة مقاومة كيميائياً.',
    keywords: ['pipes Fujairah', 'Fujairah oil gas pipes', 'marine pipes Fujairah', 'FOIZ pipe supplier'],
    focus: 'Oil & Gas, Marine & Desalination',
    focusAr: 'النفط والغاز والمشاريع البحرية وتحلية المياه',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: { text: 'Fujairah Inquiry', textAr: 'استفسار الفجيرة', link: '/contact-us?market=fujairah' },
    districts: ['FOIZ', 'Fujairah Port', 'Dibba Al Fujairah', 'Al Faseel'],
    geo: { latitude: 25.1288, longitude: 56.3264 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
    currency: 'AED',
  },
  // Kuwait — Kuwait City
  {
    slug: 'kuwait/kuwait-city',
    country: 'Kuwait',
    countryCode: 'KW',
    city: 'Kuwait City',
    cityAr: 'مدينة الكويت',
    countryAr: 'الكويت',
    title: 'Pipes / Fittings Supplier for Kuwait City & Kuwait',
    titleAr: 'مورد أنابيب / تجهيزات لمدينة الكويت والكويت',
    description: 'ISO certified Pipes / Fittings exporter for Kuwait construction and infrastructure projects. Container shipments to Shuwaikh Port, competitive bulk pricing.',
    descriptionAr: 'مصدر أنابيب / تجهيزات معتمد وفق معايير ISO لمشاريع البناء والبنية التحتية في الكويت. شحنات حاويات إلى ميناء الشويخ.',
    keywords: ['UPVC pipes Kuwait City', 'Kuwait pipe supplier', 'ISO certified Kuwait', 'Shuwaikh Port delivery'],
    focus: 'Kuwait City and nationwide supply',
    focusAr: 'مدينة الكويت والتوريد الوطني',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Kuwait Export Quote', textAr: 'عرض سعر تصدير للكويت', link: '/contact-us?market=kuwait' },
    districts: ['Kuwait City', 'Hawalli', 'Farwaniya', 'Ahmadi', 'Jahra', 'Salmiya'],
    geo: { latitude: 29.3759, longitude: 47.9774 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
    currency: 'AED',
  },
  // Qatar — Doha
  {
    slug: 'qatar/doha',
    country: 'Qatar',
    countryCode: 'QA',
    city: 'Doha',
    cityAr: 'الدوحة',
    countryAr: 'قطر',
    title: 'Pipes / Fittings Supplier for Doha & Qatar',
    titleAr: 'مورد أنابيب / تجهيزات للدوحة وقطر',
    description: 'Premium Pipes / Fittings supplier for Qatar. Serving Doha, Lusail, The Pearl, and major infrastructure projects with QCS compliant products and full technical support.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لقطر. خدمة الدوحة ولوسيل واللؤلؤة ومشاريع البنية التحتية الكبرى بمنتجات متوافقة مع QCS.',
    keywords: ['UPVC pipes Doha', 'Qatar pipe supplier', 'Lusail construction pipes', 'QCS compliant pipes'],
    focus: 'Qatar infrastructure projects',
    focusAr: 'مشاريع البنية التحتية في قطر',
    certifications: ['BS EN 1452', 'QCS Compliant', 'ISO 9001:2015'],
    cta: { text: 'Qatar Project Inquiry', textAr: 'استفسار مشروع قطر', link: '/contact-us?market=qatar' },
    districts: ['Doha', 'Lusail', 'The Pearl', 'West Bay', 'Al Wakra', 'Industrial Area'],
    geo: { latitude: 25.2854, longitude: 51.5310 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
    currency: 'AED',
  },
  // Bahrain — Manama
  {
    slug: 'bahrain/manama',
    country: 'Bahrain',
    countryCode: 'BH',
    city: 'Manama',
    cityAr: 'المنامة',
    countryAr: 'البحرين',
    title: 'Pipes / Fittings Supplier for Manama & Bahrain',
    titleAr: 'مورد أنابيب / تجهيزات للمنامة والبحرين',
    description: 'Pipes / Fittings supplier for Bahrain construction industry. Quick delivery via King Fahd Causeway or Khalifa Bin Salman Port. ISO certified products.',
    descriptionAr: 'مورد أنابيب / تجهيزات لصناعة البناء في البحرين. توصيل سريع عبر جسر الملك فهد. منتجات معتمدة ISO.',
    keywords: ['UPVC pipes Manama', 'Bahrain pipe supplier', 'Manama construction materials', 'King Fahd Causeway delivery'],
    focus: 'Bahrain and Manama supply',
    focusAr: 'التوريد في البحرين والمنامة',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Bahrain Delivery Quote', textAr: 'عرض سعر توصيل البحرين', link: '/contact-us?market=bahrain' },
    districts: ['Manama', 'Muharraq', 'Riffa', 'Hamad Town', 'Isa Town', 'Sitra'],
    geo: { latitude: 26.2285, longitude: 50.5860 },
    telephone: '+971 6 543 6781',
    deliveryTime: '2-4 business days',
    deliveryTimeAr: '٢-٤ أيام عمل',
    currency: 'AED',
  },
  // Oman — Muscat
  {
    slug: 'oman/muscat',
    country: 'Oman',
    countryCode: 'OM',
    city: 'Muscat',
    cityAr: 'مسقط',
    countryAr: 'عُمان',
    title: 'Pipes / Fittings Supplier for Muscat & Oman',
    titleAr: 'مورد أنابيب / تجهيزات لمسقط وعُمان',
    description: 'Pipes / Fittings exporter for Oman construction and infrastructure. Serving Muscat, Sohar, Salalah with delivery to Sultan Qaboos Port. ISO certified products.',
    descriptionAr: 'مصدر أنابيب / تجهيزات للبناء والبنية التحتية في عُمان. خدمة مسقط وصحار وصلالة مع توصيل لميناء السلطان قابوس.',
    keywords: ['UPVC pipes Muscat', 'Oman pipe supplier', 'Muscat construction materials', 'Sultan Qaboos Port delivery'],
    focus: 'Oman and Muscat supply',
    focusAr: 'التوريد في عُمان ومسقط',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Oman Export Inquiry', textAr: 'استفسار تصدير عُمان', link: '/contact-us?market=oman' },
    districts: ['Muscat', 'Sohar', 'Salalah', 'Nizwa', 'Sur', 'Duqm'],
    geo: { latitude: 23.5880, longitude: 58.3829 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
    currency: 'AED',
  },
];

// ============================================
// ALL REGIONAL MARKETS COMBINED
// ============================================

export const allRegionalMarkets: RegionalMarket[] = [
  ...saudiMarkets,
  ...uaeMarkets,
  ...gccMarkets,
  ...cleanSlugMarkets,
];

// Helper function to get market by slug
export function getMarketBySlug(slug: string): RegionalMarket | undefined {
  return allRegionalMarkets.find(market => market.slug === slug);
}

// Get markets by country
export function getMarketsByCountry(countryCode: string): RegionalMarket[] {
  return allRegionalMarkets.filter(market => market.countryCode === countryCode);
}
