// Regional Markets Configuration for Crown Plastic Pipes - Phase 3 AEO
// Market-specific pages with LocalBusiness schema and regional targeting

export interface RegionalMarket {
  slug: string;
  country: string;
  countryCode: string;
  city?: string;
  cityAr?: string;
  cityFr?: string;
  titleFr?: string;
  countryAr: string;
  countryFr?: string;
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  descriptionFr?: string;
  keywords: string[];
  focus: string; // e.g., 'ISO compliance', 'commercial projects'
  focusAr: string;
  focusFr?: string;
  certifications: string[];
  cta: {
    text: string;
    textAr: string;
    textFr?: string;
    link: string;
  };
  districts?: string[];
  geo?: {
    latitude: number;
    longitude: number;
  };
  telephone: string;
  deliveryTime: string;
  deliveryTimeAr: string;
  deliveryTimeFr?: string;
  currency: string;
}

// ============================================
// SAUDI ARABIA MARKET PAGES
// ============================================

export const saudiMarkets: RegionalMarket[] = [
  {
    slug: 'saudi-arabia/upvc-pipes-iso-certified',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    countryAr: 'المملكة العربية السعودية',
      countryFr: 'Arabie Saoudite',
    title: 'Export Ready & ISO Certified Pipes / Fittings for Saudi Arabia',
    titleAr: 'أنابيب / تجهيزات جاهزة للتصدير ومعتمدة ISO للسعودية',
      titleFr: 'Tuyaux/raccords prêts à l\'exportation et certifiés ISO pour l\'Arabie Saoudite',
    description: 'Crown Plastic offers ISO 9001:2015 certified Pipes / Fittings for the Saudi Arabian market. Manufactured to international quality standards (BS EN, DIN, ASTM). Bulk export to all Saudi cities.',
    descriptionAr: 'تقدم كراون بلاستيك أنابيب / تجهيزات معتمدة ISO 9001:2015 للسوق السعودي. مصنعة وفق المعايير الدولية (BS EN، DIN، ASTM). التصدير بالجملة لجميع المدن السعودية.',
      descriptionFr: 'Crown Plastic propose des tuyaux/raccords certifiés ISO 9001:2015 pour le marché saoudien. Mfabriqués selon les normes de qualité internationales (BS EN, DIN, ASTM). Exportation en vrac vers toutes les villes saoudiennes.',
    keywords: ['ISO certified UPVC pipes', 'Saudi Arabia pipe supplier', 'ASTM DIN compliant pipes', 'Saudi building materials', 'UPVC pipes KSA', 'BS EN 1452 pipes Saudi'],
    focus: 'International Quality Standards',
    focusAr: 'معايير الجودة الدولية',
      focusFr: 'Normes de qualité internationales',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785', 'DIN 8062'],
    cta: {
      text: 'Get ISO-Certified Pipes / Fittings',
      textAr: 'احصل على أنابيب / تجهيزات معتمدة ISO',
        textFr: 'Obtenez des tuyaux/raccords certifiés ISO-',
        link: '/contact-us?market=saudi-iso',
    },
    districts: ['Riyadh', 'Jeddah', 'Dammam', 'Mecca', 'Medina', 'Khobar', 'Jubail'],
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
      deliveryTimeFr: '3-5 jours ouvrables',
    currency: 'AED',
  },
  {
    slug: 'saudi-arabia/riyadh-upvc-distributor',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Riyadh',
    cityAr: 'الرياض',
      cityFr: 'Riyad',
    countryAr: 'المملكة العربية السعودية',
      countryFr: 'Arabie Saoudite',
    title: 'Pipes / Fittings Distributor in Riyadh, Saudi Arabia',
    titleAr: 'موزع أنابيب / تجهيزات في الرياض',
      titleFr: 'Distributeur de tuyaux/raccords à Riyad, Arabie Saoudite',
    description: 'Leading Pipes / Fittings distributor serving Riyadh and Central Region of Saudi Arabia. Fast delivery to Riyadh construction projects, competitive pricing, ISO certified products. Serving contractors, developers, and government projects.',
    descriptionAr: 'موزع أنابيب / تجهيزات رائد في خدمة الرياض والمنطقة الوسطى. توصيل سريع لمشاريع البناء في الرياض، أسعار تنافسية، منتجات معتمدة وفق معايير ISO.',
      descriptionFr: 'Premier distributeur de tuyaux/raccords desservant Riyad et la région centrale de l\'Arabie Saoudite. Livraison rapide pour les projets de construction de Riyad, prix compétitifs, products certifiés ISO. Au service des entrepreneurs, des développeurs et des projets gouvernementaux.',
    keywords: ['UPVC pipes Riyadh', 'Riyadh pipe distributor', 'plastic pipes Riyadh', 'construction materials Riyadh', 'UPVC supplier Central Region'],
    focus: 'Riyadh delivery and pricing',
    focusAr: 'توصيل وأسعار الرياض',
      focusFr: 'Livraison et tarifs à Riyad',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: {
      text: 'Request Quote for Riyadh Delivery',
      textAr: 'اطلب عرض سعر للتوصيل إلى الرياض',
        textFr: 'Demander un devis pour une livraison à Riyad',
        link: '/contact-us?market=riyadh',
    },
    districts: ['Al Olaya', 'Al Malaz', 'Al Naseem', 'Al Sulay', 'Al Rawdah', 'Industrial City', 'King Abdullah Financial District'],
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
      deliveryTimeFr: '3-5 jours ouvrables',
    currency: 'AED',
  },
  {
    slug: 'saudi-arabia/jeddah-upvc-wholesale',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Jeddah',
    cityAr: 'جدة',
      cityFr: 'Djeddah',
    countryAr: 'المملكة العربية السعودية',
      countryFr: 'Arabie Saoudite',
    title: 'Pipes / Fittings Wholesale Supplier in Jeddah',
    titleAr: 'مورد أنابيب / تجهيزات بالجملة في جدة',
      titleFr: 'Fournisseur en gros de tuyaux / raccords à Djeddah',
    description: 'Wholesale Pipes / Fittings supplier for Jeddah and Western Region of Saudi Arabia. Container-load shipments, bulk pricing, port delivery to Jeddah Islamic Port. Serving large construction and infrastructure projects.',
    descriptionAr: 'مورد أنابيب / تجهيزات بالجملة لجدة والمنطقة الغربية. شحنات حاويات، أسعار بالجملة، توصيل لميناء جدة الإسلامي.',
      descriptionFr: 'Fournisseur en gros de tuyaux/raccords pour Djeddah et la région occidentale de l’Arabie Saoudite. Expéditions par conteneurs, prix de gros, livraison au port islamique de Djeddah. Au service de grands projets de construction et d’infrastructures.',
    keywords: ['UPVC pipes wholesale Jeddah', 'Jeddah pipe supplier', 'bulk pipes Jeddah', 'construction materials Western Region', 'Jeddah Islamic Port delivery'],
    focus: 'Bulk orders and wholesale',
    focusAr: 'طلبات بالجملة وتجارة الجملة',
      focusFr: 'Commandes groupées et vente en gros',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: {
      text: 'Bulk Order Form for Jeddah',
      textAr: 'نموذج طلب بالجملة لجدة',
        textFr: 'Formulaire de commande groupée pour Djeddah',
        link: '/contact-us?market=jeddah-wholesale',
    },
    districts: ['Al Hamra', 'Al Rawdah', 'Al Safa', 'Industrial City', 'Jeddah Port Area', 'North Jeddah', 'South Jeddah'],
    geo: { latitude: 21.4858, longitude: 39.1925 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days via port',
    deliveryTimeAr: '٣-٥ أيام عمل عبر الميناء',
      deliveryTimeFr: '3-5 jours ouvrables via le port',
    currency: 'AED',
  },
];

// ============================================
// UAE MARKET PAGES (Additional to Phase 1)
// ============================================

export const uaeMarkets: RegionalMarket[] = [
  {
    slug: 'uae/upvc-pipes-dubai-commercial',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Dubai',
    cityAr: 'دبي',
      cityFr: 'Dubai',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings for Dubai Commercial Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع دبي التجارية',
      titleFr: 'Tuyaux/Raccords pour les projets commerciaux Dubai',
    description: 'Premium Pipes / Fittings supplier for commercial construction projects in Dubai. Serving Dubai Marina, Downtown Dubai, Business Bay, DIFC, and major developments. Delivery, project consultation, bulk pricing.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لمشاريع البناء التجارية في دبي. خدمة دبي مارينا، داون تاون دبي، بزنس باي والمشاريع الكبرى.',
      descriptionFr: 'Fournisseur de tuyaux/raccords haut de gamme pour les projets de construction commerciale à Dubai. Desservant la marina Dubai, le centre-ville Dubai, Business Bay, DIFC et les développements majeurs. Livraison, consultation de projet, prix de gros.',
    keywords: ['UPVC pipes Dubai commercial', 'Dubai construction materials', 'Business Bay pipes', 'Downtown Dubai supplier', 'commercial plumbing Dubai'],
    focus: 'Commercial projects in Dubai',
    focusAr: 'المشاريع التجارية في دبي',
      focusFr: 'Projets commerciaux à Dubai',
    certifications: ['BS EN 1452', 'DIN 8062', 'BS EN 805', 'Dubai Municipality Approved'],
    cta: {
      text: 'Commercial Project Inquiry',
      textAr: 'استفسار مشروع تجاري',
        textFr: 'Demande de projet commercial',
        link: '/contact-us?market=dubai-commercial',
    },
    districts: ['Dubai Marina', 'Downtown Dubai', 'Business Bay', 'DIFC', 'JLT', 'Dubai Hills', 'Meydan'],
    geo: { latitude: 25.2048, longitude: 55.2708 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
      deliveryTimeFr: 'Le même jour - 24 heures',
    currency: 'AED',
  },
  {
    slug: 'uae/upvc-pipes-abu-dhabi-government',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Abu Dhabi',
    cityAr: 'أبوظبي',
      cityFr: 'Abou Dhabi',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings for Abu Dhabi Government & Municipal Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع حكومة أبوظبي والبلدية',
      titleFr: 'Tuyaux/raccords pour les projets gouvernementaux et municipaux d\'Abu Dhabi',
    description: 'Certified Pipes / Fittings supplier for Abu Dhabi government, municipal, and infrastructure projects. ITC approved, Abu Dhabi Quality Mark eligible, extensive experience with ADNOC, Mubadala, and government contractors.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع حكومة أبوظبي والبلدية والبنية التحتية. معتمد من ITC، مؤهل لعلامة جودة أبوظبي.',
      descriptionFr: 'Fournisseur certifié de tuyaux/raccords pour les projets gouvernementaux, municipaux et d\'infrastructure d\'Abu Dhabi. Approuvé par l\'ITC, éligible au label de qualité d\'Abu Dhabi, vaste expérience avec ADNOC, Mubadala et les entrepreneurs gouvernementaux.',
    keywords: ['Abu Dhabi government pipes', 'municipal projects Abu Dhabi', 'ITC approved pipes', 'Abu Dhabi infrastructure', 'ADNOC contractors'],
    focus: 'Government and municipal projects',
    focusAr: 'المشاريع الحكومية والبلدية',
      focusFr: 'Projets gouvernementaux et municipaux',
    certifications: ['BS EN 1452', 'Abu Dhabi Quality Mark', 'ITC Approved', 'ISO 9001:2015'],
    cta: {
      text: 'Government Bidding Support',
      textAr: 'دعم العطاءات الحكومية',
        textFr: 'Soutien aux appels d\'offres du gouvernement',
        link: '/contact-us?market=abudhabi-government',
    },
    districts: ['Mussafah', 'KIZAD', 'Yas Island', 'Saadiyat', 'Al Reem Island', 'Khalifa City'],
    geo: { latitude: 24.4539, longitude: 54.3773 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 48 hours',
    deliveryTimeAr: 'نفس اليوم - ٤٨ ساعة',
      deliveryTimeFr: 'Le même jour - 48 heures',
    currency: 'AED',
  },
  {
    slug: 'uae/sharjah-industrial-supply',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Sharjah',
    cityAr: 'الشارقة',
      cityFr: 'Charjah',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes & Fittings for Sharjah Industrial & Manufacturing Projects',
    titleAr: 'أنابيب وتجهيزات لمشاريع الشارقة الصناعية والتصنيعية',
      titleFr: 'Tuyaux et raccords pour les projets industriels et de fabrication de Sharjah Indu',
    description: 'Leading Pipes / Fittings supplier serving Sharjah\'s industrial hub. Supplying SAIF Zone, Hamriyah Free Zone, and Sharjah Industrial Area with BS EN and ASTM certified UPVC, PVC, PP-R, PEX & HDPE systems. Bulk supply for manufacturing facilities, warehouses, and industrial infrastructure.',
    descriptionAr: 'مورد رائد للأنابيب / التجهيزات يخدم المركز الصناعي في الشارقة. توريد لمنطقة صيف والمنطقة الحرة بالحمرية والمنطقة الصناعية بالشارقة بأنظمة UPVC و PVC و PP-R و PEX و HDPE المعتمدة وفق BS EN و ASTM.',
      descriptionFr: 'Fournisseur leader de tuyaux/raccords desservant le hub industrial de Sharjah. Fourniture de la zone SAIF, de la zone franche de Hamriyah et de la zone industrielle de Sharjah Indu avec les systèmes BS EN et ASTM certified UPVC, PVC, PP-R, PEX et HDPE. Approvisionnement en vrac pour les installations de fabrication, les entrepôts et les infrastructures industrielles.',
    keywords: ['pipes Sharjah industrial', 'SAIF Zone pipe supplier', 'Hamriyah Free Zone pipes', 'Sharjah manufacturing supply', 'industrial pipes UAE', 'UPVC fittings Sharjah'],
    focus: 'Industrial Hub & Manufacturing Supply',
    focusAr: 'المركز الصناعي والتوريد التصنيعي',
      focusFr: 'Industrial Hub et approvisionnement en fabrication',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: {
      text: 'Industrial Supply Inquiry',
      textAr: 'استفسار التوريد الصناعي',
        textFr: 'InduEnquête d\'approvisionnement d\'essai',
        link: '/contact-us?market=sharjah-industrial',
    },
    districts: ['SAIF Zone', 'Hamriyah Free Zone', 'Sharjah Industrial Area', 'Al Nahda', 'Al Majaz', 'University City', 'Muwaileh'],
    geo: { latitude: 25.3463, longitude: 55.4209 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
      deliveryTimeFr: 'Livraison le jour même',
    currency: 'AED',
  },
  {
    slug: 'uae/ajman-residential-infrastructure',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ajman',
    cityAr: 'عجمان',
      cityFr: 'Ajman',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes & Fittings for Ajman Residential & Urban Development',
    titleAr: 'أنابيب وتجهيزات للتطوير السكني والحضري في عجمان',
      titleFr: 'Tuyaux et raccords pour le développement résidentiel et urbain d\'Ajman',
    description: 'Certified Pipes / Fittings supplier for Ajman\'s growing residential and urban infrastructure projects. Serving Al Zorah, Ajman Uptown, Emirates City, and new township developments with complete UPVC, PVC, PP-R, PEX & HDPE plumbing and drainage systems.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع البنية التحتية السكنية والحضرية المتنامية في عجمان. خدمة الزوراء وأبتاون عجمان وإمارات سيتي ومشاريع التطوير الجديدة بأنظمة سباكة وصرف متكاملة.',
      descriptionFr: 'Fournisseur certifié de tuyaux/raccords pour les projets d’infrastructures résidentielles et urbaines en pleine croissance d’Ajman. Desservant Al Zorah, Ajman Uptown, Emirates City et les nouveaux développements de cantons avec des systèmes complets de plomberie et de drainage UPVC, PVC, PP-R, PEX et HDPE.',
    keywords: ['pipes Ajman residential', 'Ajman plumbing supplier', 'urban infrastructure Ajman', 'Ajman construction materials', 'residential pipes UAE', 'UPVC fittings Ajman'],
    focus: 'Residential Development & Urban Infrastructure',
    focusAr: 'التطوير السكني والبنية التحتية الحضرية',
      focusFr: 'Développement résidentiel et infrastructure urbaine',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: {
      text: 'Ajman Project Quote',
      textAr: 'عرض سعر مشروع عجمان',
        textFr: 'Citation du projet Ajman',
        link: '/contact-us?market=ajman-residential',
    },
    districts: ['Al Zorah', 'Ajman Uptown', 'Emirates City', 'Al Rashidiya', 'Al Nuaimia', 'Al Jurf Industrial', 'Ajman Corniche'],
    geo: { latitude: 25.4052, longitude: 55.5136 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
      deliveryTimeFr: 'Livraison le jour même',
    currency: 'AED',
  },
  {
    slug: 'uae/umm-al-quwain-marine-industrial',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Umm Al Quwain',
    cityAr: 'أم القيوين',
      cityFr: 'Oumm Al Quwain',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes & Fittings for Umm Al Quwain Marine & Industrial Projects',
    titleAr: 'أنابيب وتجهيزات للمشاريع البحرية والصناعية في أم القيوين',
      titleFr: 'Tuyaux et raccords pour les projets marins et industriels d\'Umm Al Quwain',
    description: 'Direct-from-factory Pipes / Fittings supply from our Umm Al Quwain manufacturing facility. Shortest lead times and factory-gate pricing for marine infrastructure, industrial projects, and coastal developments. Complete UPVC, PVC, PP-R, PEX & HDPE systems manufactured on-site to BS EN and ASTM standards.',
    descriptionAr: 'توريد أنابيب / تجهيزات مباشرة من مصنعنا في أم القيوين. أقصر أوقات تسليم وأسعار المصنع للبنية التحتية البحرية والمشاريع الصناعية والتطويرات الساحلية. أنظمة UPVC و PVC و PP-R و PEX و HDPE مصنعة في الموقع وفق معايير BS EN و ASTM.',
      descriptionFr: 'Fourniture de tuyaux/raccords directement depuis l\'usine depuis notre usine de fabrication d\'Umm Al Quwain. Délais de livraison les plus courts et prix départ usine pour les infrastructures maritimes, les projets industriels et les développements côtiers. Systèmes complets UPVC, PVC, PP-R, PEX et HDPE fabriqués sur site selon BS EN et ASTM standards.',
    keywords: ['pipes Umm Al Quwain', 'UAQ marine pipes', 'factory direct pipes UAE', 'industrial pipes UAQ', 'coastal infrastructure pipes', 'UPVC manufacturer UAQ'],
    focus: 'Marine & Industrial Applications (Factory HQ)',
    focusAr: 'التطبيقات البحرية والصناعية (مقر المصنع)',
      focusFr: 'Applications marines et industrielles (QG d\'usine)',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: {
      text: 'Factory Direct Inquiry',
      textAr: 'استفسار مباشر من المصنع',
        textFr: 'Demande directe d\'usine',
        link: '/contact-us?market=uaq-marine',
    },
    districts: ['UAQ Free Trade Zone', 'UAQ Marina', 'UAQ Industrial Area', 'Al Salamah', 'Old Town', 'Al Raas'],
    geo: { latitude: 25.5647, longitude: 55.5553 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - factory direct',
    deliveryTimeAr: 'نفس اليوم - مباشرة من المصنع',
      deliveryTimeFr: 'Le jour même - directement à l\'usine',
    currency: 'AED',
  },
  {
    slug: 'uae/ras-al-khaimah-hospitality-industrial',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ras Al Khaimah',
    cityAr: 'رأس الخيمة',
      cityFr: 'Ras al-Khaimah',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes & Fittings for Ras Al Khaimah Hospitality & Industrial Zones',
    titleAr: 'أنابيب وتجهيزات لمناطق الضيافة والصناعة في رأس الخيمة',
      titleFr: 'Tuyaux et raccords pour les zones hôtelières et industrielles de Ras Al Khaimah',
    description: 'Premium Pipes / Fittings supplier for Ras Al Khaimah\'s hospitality, tourism, and industrial zone projects. Serving Al Marjan Island resorts, RAK Economic Zone, and Al Hamra developments with certified UPVC, PVC, PP-R, PEX & HDPE systems for hotels, resorts, and industrial facilities.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لمشاريع الضيافة والسياحة والمناطق الصناعية في رأس الخيمة. خدمة منتجعات جزيرة المرجان والمنطقة الاقتصادية ومشاريع الحمراء بأنظمة معتمدة للفنادق والمنتجعات والمنشآت الصناعية.',
      descriptionFr: 'Fournisseur de tuyaux/raccords haut de gamme pour les projets d\'hôtellerie, de tourisme et de zone industrielle de Ras Al Khaimah. Desservant les complexes hôteliers de l\'île d\'Al Marjan, la zone économique RAK et les développements d\'Al Hamra avec des systèmes certifiés UPVC, PVC, PP-R, PEX et HDPE pour les hôtels, les centres de villégiature et les installations industrielles du.',
    keywords: ['pipes Ras Al Khaimah', 'RAK hospitality pipes', 'Al Marjan Island plumbing', 'RAK Economic Zone pipes', 'hotel plumbing RAK', 'industrial pipes Ras Al Khaimah'],
    focus: 'Hospitality, Tourism & Industrial Zones',
    focusAr: 'الضيافة والسياحة والمناطق الصناعية',
      focusFr: 'Zones d\'hôtellerie, de tourisme et d\'industriedustrial',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: {
      text: 'RAK Project Inquiry',
      textAr: 'استفسار مشروع رأس الخيمة',
        textFr: 'Enquête sur le projet RAK',
        link: '/contact-us?market=rak-hospitality',
    },
    districts: ['Al Marjan Island', 'RAK Economic Zone', 'Al Hamra Village', 'Al Nakheel', 'Jebel Jais Area', 'RAK Free Trade Zone', 'Khuzam'],
    geo: { latitude: 25.7895, longitude: 55.9432 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
      deliveryTimeFr: 'Le même jour - 24 heures',
    currency: 'AED',
  },
  {
    slug: 'uae/fujairah-oil-gas-marine',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Fujairah',
    cityAr: 'الفجيرة',
      cityFr: 'Fujaïrah',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes & Fittings for Fujairah Oil & Gas, Marine & Desalination',
    titleAr: 'أنابيب وتجهيزات لمشاريع النفط والغاز والبحرية وتحلية المياه في الفجيرة',
      titleFr: 'Tuyaux et raccords pour le pétrole et le gaz de Fujairah, la marine et le dessalement',
    description: 'Specialized Pipes / Fittings supplier for Fujairah\'s oil & gas, marine, and desalination sectors. Serving FOIZ, Fujairah Port, and coastal industrial projects with chemically resistant UPVC, PVC, PP-R, PEX & HDPE systems built for harsh marine and industrial environments.',
    descriptionAr: 'مورد متخصص في الأنابيب / التجهيزات لقطاعات النفط والغاز والبحرية وتحلية المياه في الفجيرة. خدمة المنطقة الصناعية وميناء الفجيرة والمشاريع الساحلية بأنظمة مقاومة كيميائياً مصممة للبيئات البحرية والصناعية القاسية.',
      descriptionFr: 'Fournisseur spécialisé de tuyaux/raccords pour les secteurs du pétrole et du gaz, de la marine et du dessalement de Fujairah. Au service de FOIZ, du port de Fujairah et des projets industriels côtiers avec des systèmes UPVC, PVC, PP-R, PEX et HDPE résistants aux produits chimiques, conçus pour les environnements marins et industriels difficiles.',
    keywords: ['pipes Fujairah oil gas', 'Fujairah marine pipes', 'desalination pipes UAE', 'FOIZ pipe supplier', 'Fujairah Port infrastructure', 'chemical resistant pipes Fujairah'],
    focus: 'Oil & Gas, Marine & Desalination Projects',
    focusAr: 'النفط والغاز والمشاريع البحرية وتحلية المياه',
      focusFr: 'Projets pétroliers et gaziers, marins et de dessalement',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: {
      text: 'Fujairah Industrial Inquiry',
      textAr: 'استفسار صناعي الفجيرة',
        textFr: 'Fujairah dans l\'enquête judiciaire du',
        link: '/contact-us?market=fujairah-industrial',
    },
    districts: ['FOIZ', 'Fujairah Port', 'Dibba Al Fujairah', 'Al Faseel', 'Merashid', 'Sakamkam'],
    geo: { latitude: 25.1288, longitude: 56.3264 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
      deliveryTimeFr: 'Le même jour - 24 heures',
    currency: 'AED',
  },
];

// ============================================
// OTHER GCC MARKET PAGES
// ============================================

export const gccMarkets: RegionalMarket[] = [
  {
    slug: 'kuwait/upvc-pipes-supplier',
    country: 'Kuwait',
    countryCode: 'KW',
    city: 'Kuwait City',
    cityAr: 'مدينة الكويت',
      cityFr: 'Koweït ville',
    countryAr: 'الكويت',
      countryFr: 'Koweit',
    title: 'Pipes / Fittings Supplier for Kuwait',
    titleAr: 'مورد أنابيب / تجهيزات للكويت',
      titleFr: 'Fournisseur de tuyaux/raccords pour le Koweït',
    description: 'ISO certified Pipes / Fittings exporter for Kuwait construction and infrastructure projects. Container shipments to Shuwaikh Port, competitive bulk pricing, full documentation for Kuwaiti customs clearance.',
    descriptionAr: 'مصدر أنابيب / تجهيزات معتمد وفق معايير ISO لمشاريع البناء والبنية التحتية في الكويت. شحنات حاويات إلى ميناء الشويخ.',
      descriptionFr: 'Exportateur de tuyaux/raccords certifié ISO pour les projets de construction et d\'infrastructure du Koweït. Envois de conteneurs vers le port de Shuwaikh, prix de gros compétitifs, documentation complète pour le dédouanement koweïtien.',
    keywords: ['UPVC pipes Kuwait', 'Kuwait pipe supplier', 'ISO certified Kuwait', 'Shuwaikh Port delivery', 'Kuwait construction materials'],
    focus: 'Kuwait market export',
    focusAr: 'تصدير لسوق الكويت',
      focusFr: 'Exportation du marché du Koweït',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'ISO 9001:2015'],
    cta: {
      text: 'Request Kuwait Export Quote',
      textAr: 'اطلب عرض سعر تصدير للكويت',
        textFr: 'Demander un devis d\'exportation au Koweït',
        link: '/contact-us?market=kuwait',
    },
    districts: ['Kuwait City', 'Hawalli', 'Farwaniya', 'Ahmadi', 'Jahra', 'Salmiya'],
    geo: { latitude: 29.3759, longitude: 47.9774 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
      deliveryTimeFr: '5-7 jours ouvrables',
    currency: 'AED',
  },
  {
    slug: 'qatar/upvc-pipes-doha',
    country: 'Qatar',
    countryCode: 'QA',
    city: 'Doha',
    cityAr: 'الدوحة',
      cityFr: 'Doha',
    countryAr: 'قطر',
      countryFr: 'Qatar',
    title: 'Pipes / Fittings for Qatar Construction Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع البناء في قطر',
      titleFr: 'Tuyaux/Raccords pour les projets de construction au Qatar',
    description: 'Premium Pipes / Fittings supplier for Qatar. Serving Doha, Lusail, The Pearl, and major infrastructure projects. Experience with World Cup legacy developments. QCS compliant products with full technical support.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لقطر. خدمة الدوحة ولوسيل واللؤلؤة ومشاريع البنية التحتية الكبرى.',
      descriptionFr: 'Fournisseur de tuyaux/raccords haut de gamme pour le Qatar. Au service de Doha, Lusail, The Pearl et des grands projets d\'infrastructure. Expérience avec les développements hérités de la Coupe du monde. Products conformes QCS avec support technique complet.',
    keywords: ['UPVC pipes Qatar', 'Doha pipe supplier', 'Lusail construction', 'Qatar World Cup projects', 'QCS compliant pipes'],
    focus: 'Qatar infrastructure projects',
    focusAr: 'مشاريع البنية التحتية في قطر',
      focusFr: 'Projets d\'infrastructures au Qatar',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'QCS Compliant'],
    cta: {
      text: 'Qatar Project Inquiry',
      textAr: 'استفسار مشروع قطر',
        textFr: 'Enquête sur le projet du Qatar',
        link: '/contact-us?market=qatar',
    },
    districts: ['Doha', 'Lusail', 'The Pearl', 'West Bay', 'Al Wakra', 'Industrial Area'],
    geo: { latitude: 25.2854, longitude: 51.5310 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
      deliveryTimeFr: '5-7 jours ouvrables',
    currency: 'AED',
  },
  {
    slug: 'bahrain/upvc-pipes-manama',
    country: 'Bahrain',
    countryCode: 'BH',
    city: 'Manama',
    cityAr: 'المنامة',
      cityFr: 'Manama',
    countryAr: 'البحرين',
      countryFr: 'Bahreïn',
    title: 'Pipes / Fittings Supplier for Bahrain',
    titleAr: 'مورد أنابيب / تجهيزات للبحرين',
      titleFr: 'Fournisseur de tuyaux/raccords pour Bahreïn',
    description: 'Pipes / Fittings supplier for Bahrain construction industry. Quick delivery via King Fahd Causeway or Khalifa Bin Salman Port. Serving Manama, Muharraq, and industrial areas. ISO certified products.',
    descriptionAr: 'مورد أنابيب / تجهيزات لصناعة البناء في البحرين. توصيل سريع عبر جسر الملك فهد أو ميناء خليفة بن سلمان.',
      descriptionFr: 'Fournisseur de tuyaux / raccords pour la construction de Bahreïn à dustry. Livraison rapide via le port King Fahd Causeway ou Khalifa Bin Salman. Desservant Manama, Muharraq et les zones industrial. Products certifiés ISO.',
    keywords: ['UPVC pipes Bahrain', 'Manama pipe supplier', 'Bahrain construction materials', 'King Fahd Causeway delivery'],
    focus: 'Bahrain market',
    focusAr: 'سوق البحرين',
      focusFr: 'Marché de Bahreïn',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'ISO 9001:2015'],
    cta: {
      text: 'Bahrain Delivery Quote',
      textAr: 'عرض سعر توصيل البحرين',
        textFr: 'Bahreïn Devis de livraison',
        link: '/contact-us?market=bahrain',
    },
    districts: ['Manama', 'Muharraq', 'Riffa', 'Hamad Town', 'Isa Town', 'Sitra'],
    geo: { latitude: 26.2285, longitude: 50.5860 },
    telephone: '+971 6 543 6781',
    deliveryTime: '2-4 business days',
    deliveryTimeAr: '٢-٤ أيام عمل',
      deliveryTimeFr: '2-4 jours ouvrables',
    currency: 'AED',
  },
  {
    slug: 'oman/upvc-pipes-muscat',
    country: 'Oman',
    countryCode: 'OM',
    city: 'Muscat',
    cityAr: 'مسقط',
      cityFr: 'Muscat',
    countryAr: 'عُمان',
      countryFr: 'Oman',
    title: 'Pipes / Fittings for Oman Construction Projects',
    titleAr: 'أنابيب / تجهيزات لمشاريع البناء في عُمان',
      titleFr: 'Tuyaux/Raccords pour les projets de construction à Oman',
    description: 'Pipes / Fittings exporter for Oman construction and infrastructure. Serving Muscat, Sohar, Salalah, and all Omani governorates. Delivery to Sultan Qaboos Port. ISO certified and international standards compliant.',
    descriptionAr: 'مصدر أنابيب / تجهيزات للبناء والبنية التحتية في عُمان. خدمة مسقط وصحار وصلالة وجميع المحافظات العمانية.',
      descriptionFr: 'Exportateur de tuyaux/raccords pour la construction et les infrastructures d’Oman. Desservant Mascate, Sohar, Salalah et tous les gouvernorats omanais. Livraison au port du Sultan Qaboos. Certifié ISO et conforme aux normes internationales.',
    keywords: ['UPVC pipes Oman', 'Muscat pipe supplier', 'Oman construction materials', 'Sultan Qaboos Port delivery', 'Sohar industrial'],
    focus: 'Oman market',
    focusAr: 'سوق عُمان',
      focusFr: 'Marché d\'Oman',
    certifications: ['BS EN / ASTM Standard', 'BS EN 1452', 'ISO 9001:2015'],
    cta: {
      text: 'Oman Export Inquiry',
      textAr: 'استفسار تصدير عُمان',
        textFr: 'Enquête sur les exportations d\'Oman',
        link: '/contact-us?market=oman',
    },
    districts: ['Muscat', 'Sohar', 'Salalah', 'Nizwa', 'Sur', 'Duqm'],
    geo: { latitude: 23.5880, longitude: 58.3829 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
      deliveryTimeFr: '3-5 jours ouvrables',
    currency: 'AED',
  },
];

// ============================================
// CLEAN-SLUG MARKET ENTRIES (for Navbar links)
// These use simple geographic slugs to match the Navbar hrefs
// and are registered in generateStaticParams() via allRegionalMarkets
// ============================================

export const cleanSlugMarkets: RegionalMarket[] = [
  // Saudi Arabia — overview
  {
    slug: 'saudi-arabia/overview',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    countryAr: 'المملكة العربية السعودية',
      countryFr: 'Arabie Saoudite',
    title: 'Pipes / Fittings Supplier for Saudi Arabia | Crown Plastic',
    titleAr: 'مورد أنابيب / تجهيزات للمملكة العربية السعودية | كراون بلاستيك',
      titleFr: 'Fournisseur de tuyaux / raccords pour l\'Arabie Saoudite | Couronne en plastique',
    description: 'Crown Plastic supplies ISO 9001:2015 certified UPVC, PVC, PP-R, PEX & HDPE Pipes / Fittings to Saudi Arabia. Bulk export to all Saudi cities with competitive pricing.',
    descriptionAr: 'تورد كراون بلاستيك أنابيب / تجهيزات UPVC وPVC وPP-R وPEX وHDPE المعتمدة وفق ISO 9001:2015 للمملكة العربية السعودية. تصدير بالجملة لجميع المدن السعودية.',
      descriptionFr: 'Crown Plastic fournit des tuyaux/raccords certifiés ISO 9001:2015 UPVC, PVC, PP-R, PEX et HDPE en Arabie Saoudite. Exportation en vrac vers toutes les villes saoudiennes à des prix compétitifs.',
    keywords: ['pipes Saudi Arabia', 'UPVC pipes KSA', 'Saudi Arabia pipe supplier', 'ISO certified pipes Saudi'],
    focus: 'Saudi Arabia nationwide supply',
    focusAr: 'التوريد على مستوى المملكة العربية السعودية',
      focusFr: 'Approvisionnement national en Arabie Saoudite',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785', 'DIN 8062'],
    cta: { text: 'Get a Saudi Arabia Quote', textAr: 'احصل على عرض سعر للسعودية',
        textFr: 'Obtenez un devis en Arabie Saoudite',
        link: '/contact-us?market=saudi-arabia' },
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
      deliveryTimeFr: '3-5 jours ouvrables',
    currency: 'AED',
  },
  // Saudi Arabia — Riyadh
  {
    slug: 'saudi-arabia/riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Riyadh',
    cityAr: 'الرياض',
      cityFr: 'Riyad',
    countryAr: 'المملكة العربية السعودية',
      countryFr: 'Arabie Saoudite',
    title: 'Pipes / Fittings Supplier in Riyadh, Saudi Arabia',
    titleAr: 'مورد أنابيب / تجهيزات في الرياض، المملكة العربية السعودية',
      titleFr: 'Fournisseur de tuyaux/raccords à Riyad, Arabie Saoudite',
    description: 'Leading Pipes / Fittings supplier serving Riyadh and the Central Region of Saudi Arabia. Fast delivery, competitive pricing, ISO certified products for construction projects.',
    descriptionAr: 'مورد رائد للأنابيب / التجهيزات في الرياض والمنطقة الوسطى. توصيل سريع، أسعار تنافسية، منتجات معتمدة وفق ISO لمشاريع البناء.',
      descriptionFr: 'Premier fournisseur de tuyaux/raccords desservant Riyad et la région centrale de l\'Arabie Saoudite. Livraison rapide, prix compétitifs, products certifiés ISO pour les projets de construction.',
    keywords: ['UPVC pipes Riyadh', 'Riyadh pipe supplier', 'plastic pipes Riyadh', 'construction materials Riyadh'],
    focus: 'Riyadh delivery and pricing',
    focusAr: 'توصيل وأسعار الرياض',
      focusFr: 'Livraison et tarifs à Riyad',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: { text: 'Request Riyadh Quote', textAr: 'اطلب عرض سعر لمنطقة الرياض',
        textFr: 'Demander un devis à Riyad',
        link: '/contact-us?market=riyadh' },
    districts: ['Al Olaya', 'Al Malaz', 'Industrial City', 'King Abdullah Financial District'],
    geo: { latitude: 24.7136, longitude: 46.6753 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
      deliveryTimeFr: '3-5 jours ouvrables',
    currency: 'AED',
  },
  // Saudi Arabia — Jeddah
  {
    slug: 'saudi-arabia/jeddah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    city: 'Jeddah',
    cityAr: 'جدة',
      cityFr: 'Djeddah',
    countryAr: 'المملكة العربية السعودية',
      countryFr: 'Arabie Saoudite',
    title: 'Pipes / Fittings Supplier in Jeddah, Saudi Arabia',
    titleAr: 'مورد أنابيب / تجهيزات في جدة، المملكة العربية السعودية',
      titleFr: 'Fournisseur de tuyaux/raccords à Jeddah, Arabie Saoudite',
    description: 'Wholesale Pipes / Fittings supplier for Jeddah and Western Region. Container-load shipments, bulk pricing, port delivery to Jeddah Islamic Port.',
    descriptionAr: 'مورد أنابيب / تجهيزات بالجملة لجدة والمنطقة الغربية. شحنات حاويات، أسعار بالجملة، توصيل لميناء جدة الإسلامي.',
      descriptionFr: 'Fournisseur en gros de tuyaux/raccords pour Djeddah et la région occidentale. Expéditions par conteneurs, prix de gros, livraison au port islamique de Djeddah.',
    keywords: ['UPVC pipes Jeddah', 'Jeddah pipe supplier', 'bulk pipes Jeddah', 'Jeddah Islamic Port delivery'],
    focus: 'Bulk orders and wholesale',
    focusAr: 'طلبات بالجملة وتجارة الجملة',
      focusFr: 'Commandes groupées et vente en gros',
    certifications: ['ISO 9001:2015', 'BS EN 1452', 'ASTM D1785'],
    cta: { text: 'Bulk Order for Jeddah', textAr: 'طلب بالجملة لجدة',
        textFr: 'Commande groupée pour Djeddah',
        link: '/contact-us?market=jeddah' },
    districts: ['Al Hamra', 'Industrial City', 'Jeddah Port Area', 'North Jeddah'],
    geo: { latitude: 21.4858, longitude: 39.1925 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days via port',
    deliveryTimeAr: '٣-٥ أيام عمل عبر الميناء',
      deliveryTimeFr: '3-5 jours ouvrables via le port',
    currency: 'AED',
  },
  // UAE — Dubai
  {
    slug: 'uae/dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Dubai',
    cityAr: 'دبي',
      cityFr: 'Dubai',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings Supplier in Dubai, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في دبي، الإمارات',
      titleFr: 'Fournisseur de tuyaux/raccords à Dubai, UAE',
    description: 'Premium Pipes / Fittings supplier for Dubai commercial and residential projects. Serving Dubai Marina, Downtown Dubai, Business Bay, DIFC with same-day delivery.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لمشاريع دبي التجارية والسكنية. خدمة دبي مارينا وداون تاون دبي وبزنس باي وDIFC مع التوصيل في نفس اليوم.',
      descriptionFr: 'Fournisseur de tuyaux/raccords haut de gamme pour les projets commerciaux et résidentiels Dubai. Desservant Dubai Marina, Downtown Dubai, Business Bay, DIFC avec livraison le jour même.',
    keywords: ['UPVC pipes Dubai', 'Dubai pipe supplier', 'construction materials Dubai', 'plumbing supplier Dubai'],
    focus: 'Commercial and residential projects in Dubai',
    focusAr: 'المشاريع التجارية والسكنية في دبي',
      focusFr: 'Projets commerciaux et résidentiels à Dubai',
    certifications: ['BS EN 1452', 'DIN 8062', 'Dubai Municipality Approved', 'ISO 9001:2015'],
    cta: { text: 'Dubai Project Inquiry', textAr: 'استفسار مشروع دبي',
        textFr: 'Dubai Demande de projet',
        link: '/contact-us?market=dubai' },
    districts: ['Dubai Marina', 'Downtown Dubai', 'Business Bay', 'DIFC', 'JLT', 'Dubai Hills'],
    geo: { latitude: 25.2048, longitude: 55.2708 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
      deliveryTimeFr: 'Le même jour - 24 heures',
    currency: 'AED',
  },
  // UAE — Abu Dhabi
  {
    slug: 'uae/abu-dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Abu Dhabi',
    cityAr: 'أبوظبي',
      cityFr: 'Abou Dhabi',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings Supplier in Abu Dhabi, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في أبوظبي، الإمارات',
      titleFr: 'Fournisseur de tuyaux/raccords à Abu Dhabi, UAE',
    description: 'Certified Pipes / Fittings supplier for Abu Dhabi government, municipal, and infrastructure projects. ITC approved, Abu Dhabi Quality Mark eligible.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع حكومة أبوظبي والبلدية والبنية التحتية. معتمد من ITC.',
      descriptionFr: 'Fournisseur certifié de tuyaux/raccords pour les projets gouvernementaux, municipaux et d\'infrastructure d\'Abu Dhabi. Approuvé par l\'ITC, éligible au label de qualité d\'Abu Dhabi.',
    keywords: ['pipes Abu Dhabi', 'Abu Dhabi pipe supplier', 'municipal projects Abu Dhabi', 'ITC approved pipes'],
    focus: 'Government and municipal projects in Abu Dhabi',
    focusAr: 'المشاريع الحكومية والبلدية في أبوظبي',
      focusFr: 'Projets gouvernementaux et municipaux à Abu Dhabi',
    certifications: ['BS EN 1452', 'Abu Dhabi Quality Mark', 'ITC Approved', 'ISO 9001:2015'],
    cta: { text: 'Abu Dhabi Project Inquiry', textAr: 'استفسار مشروع أبوظبي',
        textFr: 'Enquête sur le projet d\'Abu Dhabi',
        link: '/contact-us?market=abu-dhabi' },
    districts: ['Mussafah', 'KIZAD', 'Yas Island', 'Saadiyat', 'Al Reem Island', 'Khalifa City'],
    geo: { latitude: 24.4539, longitude: 54.3773 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 48 hours',
    deliveryTimeAr: 'نفس اليوم - ٤٨ ساعة',
      deliveryTimeFr: 'Le même jour - 48 heures',
    currency: 'AED',
  },
  // UAE — Sharjah
  {
    slug: 'uae/sharjah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Sharjah',
    cityAr: 'الشارقة',
      cityFr: 'Charjah',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings Supplier in Sharjah, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في الشارقة، الإمارات',
      titleFr: 'Fournisseur de tuyaux / raccords à Sharjah, UAE',
    description: 'Pipes / Fittings supplier serving Sharjah industrial hub. Supplying SAIF Zone, Hamriyah Free Zone, and Sharjah Industrial Area with certified UPVC, PVC, PP-R, PEX & HDPE systems.',
    descriptionAr: 'مورد أنابيب / تجهيزات للمركز الصناعي في الشارقة. توريد لمنطقة صيف والمنطقة الحرة بالحمرية والمنطقة الصناعية.',
      descriptionFr: 'Fournisseur de tuyaux/raccords desservant Sharjah dans le hub dustrial. Fourniture de la zone SAIF, de la zone franche de Hamriyah et de la zone industrielle de Sharjah Indu avec des systèmes certifiés UPVC, PVC, PP-R, PEX et HDPE.',
    keywords: ['pipes Sharjah', 'SAIF Zone pipe supplier', 'Hamriyah Free Zone pipes', 'Sharjah industrial supply'],
    focus: 'Industrial Hub & Manufacturing Supply',
    focusAr: 'المركز الصناعي والتوريد التصنيعي',
      focusFr: 'Industrial Hub et approvisionnement en fabrication',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: { text: 'Sharjah Supply Inquiry', textAr: 'استفسار التوريد بالشارقة',
        textFr: 'Enquête sur l\'approvisionnement de Sharjah',
        link: '/contact-us?market=sharjah' },
    districts: ['SAIF Zone', 'Hamriyah Free Zone', 'Sharjah Industrial Area', 'Al Nahda'],
    geo: { latitude: 25.3463, longitude: 55.4209 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
      deliveryTimeFr: 'Livraison le jour même',
    currency: 'AED',
  },
  // UAE — Ajman
  {
    slug: 'uae/ajman',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ajman',
    cityAr: 'عجمان',
      cityFr: 'Ajman',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings Supplier in Ajman, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في عجمان، الإمارات',
      titleFr: 'Fournisseur de tuyaux / raccords à Ajman, UAE',
    description: 'Certified Pipes / Fittings supplier for Ajman residential and urban infrastructure projects. Serving Al Zorah, Ajman Uptown, and new developments.',
    descriptionAr: 'مورد أنابيب / تجهيزات معتمد لمشاريع البنية التحتية السكنية والحضرية في عجمان. خدمة الزوراء وأبتاون عجمان والتطويرات الجديدة.',
      descriptionFr: 'Fournisseur certifié de tuyaux/raccords pour les projets d’infrastructures résidentielles et urbaines d’Ajman. Desservant Al Zorah, Ajman Uptown et les nouveaux développements.',
    keywords: ['pipes Ajman', 'Ajman plumbing supplier', 'residential pipes Ajman', 'construction materials Ajman'],
    focus: 'Residential Development & Urban Infrastructure',
    focusAr: 'التطوير السكني والبنية التحتية الحضرية',
      focusFr: 'Développement résidentiel et infrastructure urbaine',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Ajman Project Quote', textAr: 'عرض سعر مشروع عجمان',
        textFr: 'Citation du projet Ajman',
        link: '/contact-us?market=ajman' },
    districts: ['Al Zorah', 'Ajman Uptown', 'Emirates City', 'Al Rashidiya', 'Al Nuaimia'],
    geo: { latitude: 25.4052, longitude: 55.5136 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day delivery',
    deliveryTimeAr: 'توصيل في نفس اليوم',
      deliveryTimeFr: 'Livraison le jour même',
    currency: 'AED',
  },
  // UAE — Umm Al Quwain
  {
    slug: 'uae/umm-al-quwain',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Umm Al Quwain',
    cityAr: 'أم القيوين',
      cityFr: 'Oumm Al Quwain',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings — Direct from Factory in Umm Al Quwain, UAE',
    titleAr: 'أنابيب / تجهيزات مباشرة من المصنع في أم القيوين، الإمارات',
      titleFr: 'Tuyaux/Raccords — Directement de l\'usine à Umm Al Quwain, UAE',
    description: 'Direct-from-factory Pipes / Fittings supply from our Umm Al Quwain manufacturing facility. Shortest lead times and factory-gate pricing for marine, industrial, and coastal projects.',
    descriptionAr: 'توريد أنابيب / تجهيزات مباشرة من مصنعنا في أم القيوين. أقصر أوقات تسليم وأسعار المصنع للمشاريع البحرية والصناعية والساحلية.',
      descriptionFr: 'Fourniture de tuyaux/raccords directement depuis l\'usine depuis notre usine de fabrication d\'Umm Al Quwain. Délais de livraison les plus courts et prix départ usine pour les projets marins, industriels et côtiers.',
    keywords: ['pipes Umm Al Quwain', 'UAQ factory direct pipes', 'industrial pipes UAQ', 'marine pipes UAE'],
    focus: 'Marine & Industrial (Factory HQ)',
    focusAr: 'التطبيقات البحرية والصناعية (مقر المصنع)',
      focusFr: 'Marine et Industrial (QG d\'usine)',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: { text: 'Factory Direct Inquiry', textAr: 'استفسار مباشر من المصنع',
        textFr: 'Demande directe d\'usine',
        link: '/contact-us?market=uaq' },
    districts: ['UAQ Free Trade Zone', 'UAQ Marina', 'UAQ Industrial Area'],
    geo: { latitude: 25.5647, longitude: 55.5553 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - factory direct',
    deliveryTimeAr: 'نفس اليوم - مباشرة من المصنع',
      deliveryTimeFr: 'Le jour même - directement à l\'usine',
    currency: 'AED',
  },
  // UAE — Ras Al Khaimah
  {
    slug: 'uae/ras-al-khaimah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Ras Al Khaimah',
    cityAr: 'رأس الخيمة',
      cityFr: 'Ras al-Khaimah',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings Supplier in Ras Al Khaimah, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في رأس الخيمة، الإمارات',
      titleFr: 'Fournisseur de tuyaux / raccords à Ras Al Khaimah, UAE',
    description: 'Pipes / Fittings supplier for Ras Al Khaimah hospitality, tourism, and industrial zone projects. Serving Al Marjan Island, RAK Economic Zone, and Al Hamra developments.',
    descriptionAr: 'مورد أنابيب / تجهيزات لمشاريع الضيافة والسياحة والمناطق الصناعية في رأس الخيمة. خدمة جزيرة المرجان والمنطقة الاقتصادية ومشاريع الحمراء.',
      descriptionFr: 'Fournisseur de tuyaux/raccords pour les projets d\'hôtellerie, de tourisme et de zone industrielle de Ras Al Khaimah. Desservant l\'île d\'Al Marjan, la zone économique RAK et les développements d\'Al Hamra.',
    keywords: ['pipes Ras Al Khaimah', 'RAK pipe supplier', 'Al Marjan Island plumbing', 'RAK Economic Zone pipes'],
    focus: 'Hospitality, Tourism & Industrial Zones',
    focusAr: 'الضيافة والسياحة والمناطق الصناعية',
      focusFr: 'Zones d\'hôtellerie, de tourisme et d\'industriedustrial',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'RAK Project Inquiry', textAr: 'استفسار مشروع رأس الخيمة',
        textFr: 'Enquête sur le projet RAK',
        link: '/contact-us?market=rak' },
    districts: ['Al Marjan Island', 'RAK Economic Zone', 'Al Hamra Village', 'RAK Free Trade Zone'],
    geo: { latitude: 25.7895, longitude: 55.9432 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
      deliveryTimeFr: 'Le même jour - 24 heures',
    currency: 'AED',
  },
  // UAE — Fujairah
  {
    slug: 'uae/fujairah',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Fujairah',
    cityAr: 'الفجيرة',
      cityFr: 'Fujaïrah',
    countryAr: 'الإمارات العربية المتحدة',
      countryFr: 'Émirats arabes unis',
    title: 'Pipes / Fittings Supplier in Fujairah, UAE',
    titleAr: 'مورد أنابيب / تجهيزات في الفجيرة، الإمارات',
      titleFr: 'Fournisseur de tuyaux / raccords à Fujairah, UAE',
    description: 'Specialized Pipes / Fittings supplier for Fujairah oil & gas, marine, and desalination sectors. Serving FOIZ, Fujairah Port with chemically resistant UPVC, PVC, PP-R, PEX & HDPE systems.',
    descriptionAr: 'مورد متخصص في أنابيب / تجهيزات لقطاعات النفط والغاز والبحرية وتحلية المياه في الفجيرة. خدمة المنطقة الصناعية وميناء الفجيرة بأنظمة مقاومة كيميائياً.',
      descriptionFr: 'Fournisseur spécialisé de tuyaux/raccords pour les secteurs du pétrole et du gaz, de la marine et du dessalement de Fujairah. Desservant FOIZ, port de Fujairah, avec les systèmes UPVC, PVC, PP-R, PEX et HDPE résistants aux produits chimiques.',
    keywords: ['pipes Fujairah', 'Fujairah oil gas pipes', 'marine pipes Fujairah', 'FOIZ pipe supplier'],
    focus: 'Oil & Gas, Marine & Desalination',
    focusAr: 'النفط والغاز والمشاريع البحرية وتحلية المياه',
      focusFr: 'Pétrole et gaz, marine et dessalement',
    certifications: ['BS EN 1452', 'ASTM D1785', 'ISO 9001:2015', 'DIN 8062'],
    cta: { text: 'Fujairah Inquiry', textAr: 'استفسار الفجيرة',
        textFr: 'Enquête sur Fujaïrah',
        link: '/contact-us?market=fujairah' },
    districts: ['FOIZ', 'Fujairah Port', 'Dibba Al Fujairah', 'Al Faseel'],
    geo: { latitude: 25.1288, longitude: 56.3264 },
    telephone: '+971 6 543 6781',
    deliveryTime: 'Same day - 24 hours',
    deliveryTimeAr: 'نفس اليوم - ٢٤ ساعة',
      deliveryTimeFr: 'Le même jour - 24 heures',
    currency: 'AED',
  },
  // Kuwait — Kuwait City
  {
    slug: 'kuwait/kuwait-city',
    country: 'Kuwait',
    countryCode: 'KW',
    city: 'Kuwait City',
    cityAr: 'مدينة الكويت',
      cityFr: 'Koweït ville',
    countryAr: 'الكويت',
      countryFr: 'Koweit',
    title: 'Pipes / Fittings Supplier for Kuwait City & Kuwait',
    titleAr: 'مورد أنابيب / تجهيزات لمدينة الكويت والكويت',
      titleFr: 'Fournisseur de tuyaux/raccords pour la ville de Koweït et le Koweït',
    description: 'ISO certified Pipes / Fittings exporter for Kuwait construction and infrastructure projects. Container shipments to Shuwaikh Port, competitive bulk pricing.',
    descriptionAr: 'مصدر أنابيب / تجهيزات معتمد وفق معايير ISO لمشاريع البناء والبنية التحتية في الكويت. شحنات حاويات إلى ميناء الشويخ.',
      descriptionFr: 'Exportateur de tuyaux/raccords certifié ISO pour les projets de construction et d\'infrastructure du Koweït. Expéditions de conteneurs vers le port de Shuwaikh, prix de gros compétitifs.',
    keywords: ['UPVC pipes Kuwait City', 'Kuwait pipe supplier', 'ISO certified Kuwait', 'Shuwaikh Port delivery'],
    focus: 'Kuwait City and nationwide supply',
    focusAr: 'مدينة الكويت والتوريد الوطني',
      focusFr: 'Koweït City et approvisionnement national',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Kuwait Export Quote', textAr: 'عرض سعر تصدير للكويت',
        textFr: 'Cotation d\'exportation du Koweït',
        link: '/contact-us?market=kuwait' },
    districts: ['Kuwait City', 'Hawalli', 'Farwaniya', 'Ahmadi', 'Jahra', 'Salmiya'],
    geo: { latitude: 29.3759, longitude: 47.9774 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
      deliveryTimeFr: '5-7 jours ouvrables',
    currency: 'AED',
  },
  // Qatar — Doha
  {
    slug: 'qatar/doha',
    country: 'Qatar',
    countryCode: 'QA',
    city: 'Doha',
    cityAr: 'الدوحة',
      cityFr: 'Doha',
    countryAr: 'قطر',
      countryFr: 'Qatar',
    title: 'Pipes / Fittings Supplier for Doha & Qatar',
    titleAr: 'مورد أنابيب / تجهيزات للدوحة وقطر',
      titleFr: 'Fournisseur de tuyaux/raccords pour Doha et le Qatar',
    description: 'Premium Pipes / Fittings supplier for Qatar. Serving Doha, Lusail, The Pearl, and major infrastructure projects with QCS compliant products and full technical support.',
    descriptionAr: 'مورد أنابيب / تجهيزات متميز لقطر. خدمة الدوحة ولوسيل واللؤلؤة ومشاريع البنية التحتية الكبرى بمنتجات متوافقة مع QCS.',
      descriptionFr: 'Fournisseur de tuyaux/raccords haut de gamme pour le Qatar. Au service de Doha, Lusail, The Pearl et des grands projets d\'infrastructure avec des products conformes au QCS et un support technique complet.',
    keywords: ['UPVC pipes Doha', 'Qatar pipe supplier', 'Lusail construction pipes', 'QCS compliant pipes'],
    focus: 'Qatar infrastructure projects',
    focusAr: 'مشاريع البنية التحتية في قطر',
      focusFr: 'Projets d\'infrastructures au Qatar',
    certifications: ['BS EN 1452', 'QCS Compliant', 'ISO 9001:2015'],
    cta: { text: 'Qatar Project Inquiry', textAr: 'استفسار مشروع قطر',
        textFr: 'Enquête sur le projet du Qatar',
        link: '/contact-us?market=qatar' },
    districts: ['Doha', 'Lusail', 'The Pearl', 'West Bay', 'Al Wakra', 'Industrial Area'],
    geo: { latitude: 25.2854, longitude: 51.5310 },
    telephone: '+971 6 543 6781',
    deliveryTime: '5-7 business days',
    deliveryTimeAr: '٥-٧ أيام عمل',
      deliveryTimeFr: '5-7 jours ouvrables',
    currency: 'AED',
  },
  // Bahrain — Manama
  {
    slug: 'bahrain/manama',
    country: 'Bahrain',
    countryCode: 'BH',
    city: 'Manama',
    cityAr: 'المنامة',
      cityFr: 'Manama',
    countryAr: 'البحرين',
      countryFr: 'Bahreïn',
    title: 'Pipes / Fittings Supplier for Manama & Bahrain',
    titleAr: 'مورد أنابيب / تجهيزات للمنامة والبحرين',
      titleFr: 'Fournisseur de tuyaux/raccords pour Manama et Bahreïn',
    description: 'Pipes / Fittings supplier for Bahrain construction industry. Quick delivery via King Fahd Causeway or Khalifa Bin Salman Port. ISO certified products.',
    descriptionAr: 'مورد أنابيب / تجهيزات لصناعة البناء في البحرين. توصيل سريع عبر جسر الملك فهد. منتجات معتمدة ISO.',
      descriptionFr: 'Fournisseur de tuyaux / raccords pour la construction de Bahreïn à dustry. Livraison rapide via le port King Fahd Causeway ou Khalifa Bin Salman. Products certifiés ISO.',
    keywords: ['UPVC pipes Manama', 'Bahrain pipe supplier', 'Manama construction materials', 'King Fahd Causeway delivery'],
    focus: 'Bahrain and Manama supply',
    focusAr: 'التوريد في البحرين والمنامة',
      focusFr: 'Approvisionnement de Bahreïn et Manama',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Bahrain Delivery Quote', textAr: 'عرض سعر توصيل البحرين',
        textFr: 'Bahreïn Devis de livraison',
        link: '/contact-us?market=bahrain' },
    districts: ['Manama', 'Muharraq', 'Riffa', 'Hamad Town', 'Isa Town', 'Sitra'],
    geo: { latitude: 26.2285, longitude: 50.5860 },
    telephone: '+971 6 543 6781',
    deliveryTime: '2-4 business days',
    deliveryTimeAr: '٢-٤ أيام عمل',
      deliveryTimeFr: '2-4 jours ouvrables',
    currency: 'AED',
  },
  // Oman — Muscat
  {
    slug: 'oman/muscat',
    country: 'Oman',
    countryCode: 'OM',
    city: 'Muscat',
    cityAr: 'مسقط',
      cityFr: 'Muscat',
    countryAr: 'عُمان',
      countryFr: 'Oman',
    title: 'Pipes / Fittings Supplier for Muscat & Oman',
    titleAr: 'مورد أنابيب / تجهيزات لمسقط وعُمان',
      titleFr: 'Fournisseur de tuyaux/raccords pour Mascate et Oman',
    description: 'Pipes / Fittings exporter for Oman construction and infrastructure. Serving Muscat, Sohar, Salalah with delivery to Sultan Qaboos Port. ISO certified products.',
    descriptionAr: 'مصدر أنابيب / تجهيزات للبناء والبنية التحتية في عُمان. خدمة مسقط وصحار وصلالة مع توصيل لميناء السلطان قابوس.',
      descriptionFr: 'Exportateur de tuyaux/raccords pour la construction et les infrastructures d’Oman. Desservant Mascate, Sohar, Salalah avec livraison au port du Sultan Qaboos. Produits certifiés ISO.',
    keywords: ['UPVC pipes Muscat', 'Oman pipe supplier', 'Muscat construction materials', 'Sultan Qaboos Port delivery'],
    focus: 'Oman and Muscat supply',
    focusAr: 'التوريد في عُمان ومسقط',
      focusFr: 'Approvisionnement d\'Oman et de Mascate',
    certifications: ['BS EN 1452', 'ISO 9001:2015', 'ASTM D1785'],
    cta: { text: 'Oman Export Inquiry', textAr: 'استفسار تصدير عُمان',
        textFr: 'Enquête sur les exportations d\'Oman',
        link: '/contact-us?market=oman' },
    districts: ['Muscat', 'Sohar', 'Salalah', 'Nizwa', 'Sur', 'Duqm'],
    geo: { latitude: 23.5880, longitude: 58.3829 },
    telephone: '+971 6 543 6781',
    deliveryTime: '3-5 business days',
    deliveryTimeAr: '٣-٥ أيام عمل',
      deliveryTimeFr: '3-5 jours ouvrables',
    currency: 'AED',
  },
];

// ============================================
// ALL REGIONAL MARKETS COMBINED
// ============================================

export const allRegionalMarkets: RegionalMarket[] = [
  ...saudiMarkets,
  ...uaeMarkets,
  ...gccMarkets,
  ...cleanSlugMarkets,
];

// Helper function to get market by slug
export function getMarketBySlug(slug: string): RegionalMarket | undefined {
  return allRegionalMarkets.find(market => market.slug === slug);
}

// Get markets by country
export function getMarketsByCountry(countryCode: string): RegionalMarket[] {
  return allRegionalMarkets.filter(market => market.countryCode === countryCode);
}
