// Products configuration for Crown Plastic Pipes
// Trilingual structure - English names with Arabic & French translations
// STANDARDISED PRODUCT CATALOG - Phase 1 Taxonomy + Phase 2 Arabic Sync + Phase 3 French

export interface SubProduct {
  slug: string;
  name: string;
  nameAr?: string;
  nameFr?: string;
  shortLabel?: string;  // Short label for compact UI (e.g., "DIN 8063")
  shortLabelAr?: string;
  shortLabelFr?: string;
  standards: string[];  // Standards stay in English always
  shortDescription: string;
  shortDescriptionAr?: string;
  shortDescriptionFr?: string;
  features?: string[];
  featuresAr?: string[];
  featuresFr?: string[];
  image?: string;  // Sub-product specific image, falls back to category image
}

export interface ProductCategory {
  slug: string;
  name: string;
  nameAr?: string;
  nameFr?: string;
  shortDescription: string;
  shortDescriptionAr?: string;
  shortDescriptionFr?: string;
  icon: string;
  image?: string;
  subProducts: SubProduct[];
}

// ═══════════════════════════════════════════════════════════════════════════════
// AUTHORITATIVE PRODUCT CATALOG
// Only categories and families listed here should appear in UI/nav/sitemap
// ═══════════════════════════════════════════════════════════════════════════════

export const productCategories: ProductCategory[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // 1) UPVC DRAINAGE PIPES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'upvc-drainage-pipes',
    name: 'UPVC Drainage Pipes',
    nameAr: 'أنابيب الصرف UPVC',
    nameFr: 'Tuyaux d\'Évacuation UPVC',
    shortDescription: 'Dubai Municipality and ADSSC-compliant drainage Pipes / Fittings to BS 5255 / BS EN 1329-1:2014 and BS EN 1401-1. Manufactured with ±0.2 mm wall thickness tolerance — 60% tighter than typical imports. Vicat softening at 79°C sustains structural integrity at Gulf ground temperatures. Deployed on Business Bay Tower D: 12,500 LM of BS EN 1329 drainage stacks.',
    shortDescriptionAr: 'أنابيب / تجهيزات صرف متوافقة مع بلدية دبي وأدسك وفق BS 5255 / BS EN 1329-1:2014 و BS EN 1401-1. مصنعة بتفاوت سمك جدار ±0.2 مم — أدق بنسبة 60% من الواردات. تليين فيكات عند 79°C يحافظ على السلامة الهيكلية في درجات حرارة تربة الخليج. تم توريدها لمجمع بزنس باي التجاري — البرج D: 12,500 متر طولي من أنابيب صرف BS EN 1329.',
    shortDescriptionFr: 'Tuyaux / Raccords d\'évacuation conformes à la Municipalité de Dubaï et à l\'ADSSC selon BS 5255 / BS EN 1329-1:2014 et BS EN 1401-1. Fabriqués avec une tolérance d\'épaisseur de paroi de ±0,2 mm — 60 % plus précise que les importations standard. Ramollissement Vicat à 79 °C assurant l\'intégrité structurelle aux températures du sol du Golfe. Déployés sur Business Bay Tour D : 12 500 ML de colonnes d\'évacuation BS EN 1329.',
    icon: '🔧',
    image: '/images/products/sub_products/Drainage.jpg',
    subProducts: [
      {
        slug: 'upvc-drainage-pipes-bs5255-bs-en-1329',
        name: 'UPVC Drainage Pipes BS 5255/BS EN 1329-1:2014 & BS 4514/BS EN 1329-1:2014',
        nameAr: 'أنابيب الصرف UPVC وفق BS 5255/BS EN 1329-1:2014 و BS 4514/BS EN 1329-1:2014',
        nameFr: 'Tuyaux d\'Évacuation UPVC BS 5255/BS EN 1329-1:2014 & BS 4514/BS EN 1329-1:2014',
        shortLabel: 'BS 5255 / BS EN 1329-1:2014',
        shortLabelAr: 'BS 5255 / BS EN 1329-1:2014',
        shortLabelFr: 'BS 5255 / BS EN 1329-1:2014',
        standards: ['BS 5255', 'BS EN 1329-1:2014', 'BS 4514'],
        shortDescription: 'Above-ground soil and waste discharge drainage pipes certified to BS 5255/BS EN 1329-1:2014 & BS 4514/BS EN 1329-1:2014.',
        shortDescriptionAr: 'أنابيب الصرف فوق الأرض لتصريف التربة والنفايات معتمدة وفق BS 5255/BS EN 1329-1:2014 و BS 4514/BS EN 1329-1:2014.',
        shortDescriptionFr: 'Tuyaux d\'évacuation aériens pour eaux usées certifiés BS 5255/BS EN 1329-1:2014 & BS 4514/BS EN 1329-1:2014.',
        features: ['BS 5255 & BS EN 1329-1:2014 certified', 'Smooth internal bore prevents scaling', 'Chemical & corrosion resistant', 'Solvent cement jointing', '50+ year service life'],
        featuresAr: ['معتمدة وفق BS 5255 و BS EN 1329-1:2014', 'تجويف داخلي أملس يمنع التكلس', 'مقاوم للمواد الكيميائية والتآكل', 'وصل بأسمنت المذيب', 'عمر خدمة يزيد عن 50 سنة'],
        featuresFr: ['Certifié BS 5255 & BS EN 1329-1:2014', 'Alésage interne lisse empêchant le tartre', 'Résistant aux produits chimiques et à la corrosion', 'Assemblage par collage au solvant', 'Durée de vie supérieure à 50 ans'],
        image: '/images/products/cover/upvc-drainage/pipes/upvcdrainagepipesbs5255.png',
      },
      {
        slug: 'upvc-drainage-pipes-bs-en-1401',
        name: 'UPVC Drainage Pipes BS EN 1401-1 (BS 4660 & BS 5481)',
        nameAr: 'أنابيب الصرف UPVC وفق BS EN 1401-1 (BS 4660 و BS 5481)',
        nameFr: 'Tuyaux d\'Évacuation UPVC BS EN 1401-1 (BS 4660 & BS 5481)',
        shortLabel: 'BS EN 1401-1',
        shortLabelAr: 'BS EN 1401-1',
        shortLabelFr: 'BS EN 1401-1',
        standards: ['BS EN 1401-1', 'BS 4660', 'BS 5481'],
        shortDescription: 'Underground drainage pipes certified to BS EN 1401-1 (supersedes BS 4660 & BS 5481).',
        shortDescriptionAr: 'أنابيب الصرف تحت الأرض معتمدة وفق BS EN 1401-1 (تحل محل BS 4660 و BS 5481).',
        shortDescriptionFr: 'Tuyaux d\'évacuation souterrains certifiés BS EN 1401-1 (remplace BS 4660 & BS 5481).',
        features: ['BS EN 1401-1 certified (supersedes BS 4660 & BS 5481)', 'High ring stiffness for underground loading', 'Root-resistant construction', 'Orange colour for underground ID', '50+ year service life'],
        featuresAr: ['معتمدة وفق BS EN 1401-1 (تحل محل BS 4660 و BS 5481)', 'صلابة حلقية عالية لأحمال تحت الأرض', 'بناء مقاوم للجذور', 'لون برتقالي للتعرف تحت الأرض', 'عمر خدمة يزيد عن 50 سنة'],
        featuresFr: ['Certifié BS EN 1401-1 (remplace BS 4660 & BS 5481)', 'Rigidité annulaire élevée pour charges souterraines', 'Construction résistante aux racines', 'Couleur orange pour identification souterraine', 'Durée de vie supérieure à 50 ans'],
        image: '/images/products/cover/upvc-drainage/pipes/upvcdrainagepipesbs1401.png',
      },
      {
        slug: 'upvc-drainage-pipes-non-standard',
        name: 'UPVC Drainage Non-Standard Pipes',
        nameAr: 'أنابيب الصرف UPVC غير القياسية',
        nameFr: 'Tuyaux d\'Évacuation UPVC Non Standard',
        shortLabel: 'Non-Standard',
        shortLabelAr: 'غير قياسية',
        shortLabelFr: 'Non Standard',
        standards: ['Crown Specification'],
        shortDescription: 'Non-standard UPVC drainage pipes for specialized project requirements.',
        shortDescriptionAr: 'أنابيب صرف UPVC غير قياسية لمتطلبات المشاريع المتخصصة.',
        shortDescriptionFr: 'Tuyaux d\'évacuation UPVC hors normes pour exigences de projets spécialisés.',
        features: ['Custom dimensions outside BS/EN scope', 'Same high-grade PVC-U compound', 'Sizes from 1¼″ to 12″', 'Ideal for retrofit & renovation', 'Chemical resistant'],
        featuresAr: ['أبعاد مخصصة خارج نطاق معايير BS/EN', 'نفس مركب PVC-U عالي الجودة', 'مقاسات من 1¼″ إلى 12″', 'مثالي للتجديد والترميم', 'مقاوم للمواد الكيميائية'],
        featuresFr: ['Dimensions personnalisées hors normes BS/EN', 'Même compound PVC-U haute qualité', 'Diamètres de 1¼″ à 12″', 'Idéal pour rénovation et réhabilitation', 'Résistant aux produits chimiques'],
        image: '/images/products/cover/upvc-drainage/pipes/upvcdrainagepipesnonstandard.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 2) UPVC DRAINAGE FITTINGS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'upvc-drainage-fittings',
    name: 'UPVC Drainage Fittings',
    nameAr: 'وصلات الصرف UPVC',
    nameFr: 'Raccords d\'Évacuation UPVC',
    shortDescription: 'DM-approved drainage Pipes / Fittings to BS EN 1329-1:2014 and BS EN 1401 with pushfit variants. Wall thickness tolerance held at ±0.3 mm across all fitting geometries. Vicat softening at 79°C validated under Gulf ambient cycling. Supplied 4,800 fittings to Saadiyat Cultural District drainage systems in Abu Dhabi.',
    shortDescriptionAr: 'وصلات صرف معتمدة من بلدية دبي وفق BS EN 1329-1:2014 و BS EN 1401 مع متغيرات الدفع. تفاوت سمك الجدار ±0.3 مم عبر جميع أشكال الوصلات. تليين فيكات عند 79°C معتمد تحت دورات حرارة الخليج. تم توريد 4,800 وصلة لأنظمة صرف المنطقة الثقافية في جزيرة السعديات بأبوظبي.',
    shortDescriptionFr: 'Raccords d\'évacuation approuvés par la Municipalité de Dubaï selon BS EN 1329-1:2014 et BS EN 1401 avec variantes à emboîtement. Tolérance d\'épaisseur de paroi de ±0,3 mm sur toutes les géométries. Ramollissement Vicat à 79 °C validé sous cycles ambiants du Golfe. 4 800 raccords fournis pour les systèmes d\'évacuation du District Culturel de Saadiyat à Abu Dhabi.',
    icon: '🔩',
    image: '/images/products/sub_products/Drainage.jpg',
    subProducts: [
      {
        slug: 'upvc-drainage-fittings-bs-en-1329',
        name: 'UPVC Drainage Fittings BS EN 1329-1:2014 (Supersedes BS 5255 & BS 4514)',
        nameAr: 'وصلات الصرف UPVC وفق BS EN 1329-1:2014 (تحل محل BS 5255 و BS 4514)',
        nameFr: 'Raccords d\'Évacuation UPVC BS EN 1329-1:2014 (Remplace BS 5255 & BS 4514)',
        shortLabel: 'BS EN 1329-1:2014',
        shortLabelAr: 'BS EN 1329-1:2014',
        shortLabelFr: 'BS EN 1329-1:2014',
        standards: ['BS EN 1329-1:2014', 'Supersedes BS 5255', 'Supersedes BS 4514'],
        shortDescription: 'Above-ground drainage fittings certified to BS EN 1329-1:2014.',
        shortDescriptionAr: 'وصلات الصرف فوق الأرض معتمدة وفق BS EN 1329-1:2014.',
        shortDescriptionFr: 'Raccords d\'évacuation aériens certifiés BS EN 1329-1:2014.',
        features: ['BS EN 1329-1:2014 certified', 'Sizes from 1½″ to 8″', '24 fitting types available', 'Smooth internal bore', 'Solvent cement jointing'],
        featuresAr: ['معتمدة وفق BS EN 1329-1:2014', 'مقاسات من 1½″ إلى 8″', '24 نوع وصلة متوفرة', 'تجويف داخلي أملس', 'وصل بأسمنت المذيب'],
        featuresFr: ['Certifié BS EN 1329-1:2014', 'Diamètres de 1½″ à 8″', '24 types de raccords disponibles', 'Alésage interne lisse', 'Assemblage par collage au solvant'],
        image: '/images/products/cover/upvc-drainage/fittings/BS EN 1329-12014.png',
      },
      {
        slug: 'upvc-drainage-fittings-bs-en-1401',
        name: 'UPVC Drainage Fittings BS EN 1401 (Supersedes BS 4660 & BS 5481)',
        nameAr: 'وصلات الصرف UPVC وفق BS EN 1401 (تحل محل BS 4660 و BS 5481)',
        nameFr: 'Raccords d\'Évacuation UPVC BS EN 1401 (Remplace BS 4660 & BS 5481)',
        shortLabel: 'BS EN 1401',
        shortLabelAr: 'BS EN 1401',
        shortLabelFr: 'BS EN 1401',
        standards: ['BS EN 1401', 'Supersedes BS 4660', 'Supersedes BS 5481'],
        shortDescription: 'Underground drainage fittings certified to BS EN 1401.',
        shortDescriptionAr: 'وصلات الصرف تحت الأرض معتمدة وفق BS EN 1401.',
        shortDescriptionFr: 'Raccords d\'évacuation souterrains certifiés BS EN 1401.',
        features: ['BS EN 1401 certified', 'Underground sewerage rated', '8 fitting types available', 'High chemical resistance', 'Ring-seal jointing'],
        featuresAr: ['معتمدة وفق BS EN 1401', 'مصنفة للصرف الصحي تحت الأرض', '8 أنواع وصلات متوفرة', 'مقاومة كيميائية عالية', 'وصل بالحلقة المانعة'],
        featuresFr: ['Certifié BS EN 1401', 'Classement assainissement souterrain', '8 types de raccords disponibles', 'Haute résistance chimique', 'Assemblage par joint à bague'],
        image: '/images/products/cover/upvc-drainage/fittings/BS EN 1401.png',
      },
      {
        slug: 'upvc-drainage-fittings-pushfit',
        name: 'UPVC Drainage Pushfit Fittings',
        nameAr: 'وصلات الصرف UPVC بالدفع',
        nameFr: 'Raccords d\'Évacuation UPVC à Emboîtement',
        shortLabel: 'Pushfit',
        shortLabelAr: 'وصلات الدفع',
        shortLabelFr: 'Emboîtement',
        standards: ['Crown Specification'],
        shortDescription: 'Push-fit drainage fittings for quick and secure connections.',
        shortDescriptionAr: 'وصلات صرف بالدفع للتوصيل السريع والآمن.',
        shortDescriptionFr: 'Raccords d\'évacuation à emboîtement pour connexions rapides et sécurisées.',
        features: ['Tool-free push-fit installation', 'Integral rubber ring seals', 'Easy disassembly for maintenance', 'Compatible with UPVC drainage pipes'],
        featuresAr: ['تركيب بالدفع بدون أدوات', 'حلقات مطاطية مدمجة', 'سهولة التفكيك للصيانة', 'متوافقة مع أنابيب الصرف UPVC'],
        featuresFr: ['Installation à emboîtement sans outils', 'Joints à bague caoutchouc intégrés', 'Démontage facile pour maintenance', 'Compatible avec tuyaux d\'évacuation UPVC'],
        image: '/images/products/cover/upvc-drainage/fittings/Pushfit drainage fittings.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 3) PVC HIGH PRESSURE PIPES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'pvc-high-pressure-pipes',
    name: 'PVC High Pressure Pipes',
    nameAr: 'أنابيب الضغط العالي PVC',
    nameFr: 'Tuyaux Haute Pression PVC',
    shortDescription: 'Dubai Municipality and Civil Defense-certified pressure Pipes / Fittings to ISO 4422-2:1996, DIN 8061/62, BS EN ISO 1452-2, BS 3505, BS 3506, ASTM D 1785, and ASTM D 2241. Factory-tested minimum burst pressure: 42.0 MPa. At 50°C Gulf peak ambient, derating factor 0.50 retains PN8 effective working capacity on PN16 mains. Deployed on Dubai Creek Harbour Phase 3: 48,000 LM of PN16 pressure mains.',
    shortDescriptionAr: 'أنابيب / تجهيزات ضغط معتمدة من بلدية دبي والدفاع المدني وفق ISO 4422-2:1996 و DIN 8061/62 و BS EN ISO 1452-2 و BS 3505 و BS 3506 و ASTM D 1785 و ASTM D 2241. أدنى ضغط انفجار مختبر في المصنع: 42.0 ميجاباسكال. عند ذروة حرارة الخليج 50°C، معامل التخفيض 0.50 يحافظ على قدرة تشغيل فعالة PN8 لأنابيب PN16. تم التوريد لمشروع دبي كريك هاربور المرحلة 3: 48,000 متر طولي من أنابيب الضغط PN16.',
    shortDescriptionFr: 'Tuyaux / Raccords pression certifiés par la Municipalité de Dubaï et la Défense Civile selon ISO 4422-2:1996, DIN 8061/62, BS EN ISO 1452-2, BS 3505, BS 3506, ASTM D 1785 et ASTM D 2241. Pression d\'éclatement minimale testée en usine : 42,0 MPa. À 50 °C (pic ambiant du Golfe), le facteur de déclassement 0,50 maintient une capacité de service effective PN8 sur conduites PN16. Déployés sur Dubai Creek Harbour Phase 3 : 48 000 ML de conduites pression PN16.',
    icon: '💧',
    image: '/images/products/sub_products/PVC.jpg',
    subProducts: [
      {
        slug: 'pvc-hp-pipes-iso-4422',
        name: 'PVC High Pressure Pipes ISO 4422-2:1996 (Superseded by ISO 1452-2/BS EN 1452:2009) (mm)',
        nameAr: 'أنابيب الضغط العالي PVC وفق ISO 4422-2:1996 (حلت محلها ISO 1452-2/BS EN 1452:2009) (مم)',
        nameFr: 'Tuyaux Haute Pression PVC ISO 4422-2:1996 (Remplacé par ISO 1452-2/BS EN 1452:2009) (mm)',
        shortLabel: 'ISO 4422-2:1996',
        shortLabelAr: 'ISO 4422-2:1996',
        shortLabelFr: 'ISO 4422-2:1996',
        standards: ['ISO 4422-2:1996', 'ISO 1452-2', 'BS EN 1452:2009'],
        shortDescription: 'PVC pressure pipes to ISO 4422-2:1996 standard (metric).',
        shortDescriptionAr: 'أنابيب ضغط PVC وفق معيار ISO 4422-2:1996 (متري).',
        shortDescriptionFr: 'Tuyaux pression PVC selon norme ISO 4422-2:1996 (métrique).',
        features: ['ISO 4422-2:1996 certified', 'PN 6/10/16 pressure classes', 'Sizes 20–400 mm', 'Potable water approved', 'UV stabilised for Gulf climate'],
        featuresAr: ['معتمدة وفق ISO 4422-2:1996', 'فئات ضغط PN 6/10/16', 'مقاسات 20–400 مم', 'معتمدة لمياه الشرب', 'مثبّتة ضد الأشعة فوق البنفسجية لمناخ الخليج'],
        featuresFr: ['Certifié ISO 4422-2:1996', 'Classes de pression PN 6/10/16', 'Diamètres 20–400 mm', 'Approuvé eau potable', 'Stabilisé UV pour climat du Golfe'],
        image: '/images/products/cover/pvc high pressure/CROWN PLASTIC PVC HIGH PRESSURE PIPE ISO 4422-21996.png',
      },
      {
        slug: 'pvc-hp-pipes-din-8061-62',
        name: 'PVC High Pressure Pipes DIN 8061/62: 2009 Equivalent to SASO 14-15: 1998 (mm)',
        nameAr: 'أنابيب الضغط العالي PVC وفق DIN 8061/62: 2009 المكافئ لـ SASO 14-15: 1998 (مم)',
        nameFr: 'Tuyaux Haute Pression PVC DIN 8061/62: 2009 Équivalent SASO 14-15: 1998 (mm)',
        shortLabel: 'DIN 8061/62',
        shortLabelAr: 'DIN 8061/62',
        shortLabelFr: 'DIN 8061/62',
        standards: ['DIN 8061', 'DIN 8062', 'SASO 14-15:1998'],
        shortDescription: 'PVC pressure pipes to DIN 8061/62 standard, equivalent to SASO 14-15 (metric).',
        shortDescriptionAr: 'أنابيب ضغط PVC وفق معيار DIN 8061/62 المكافئ لـ SASO 14-15 (متري).',
        shortDescriptionFr: 'Tuyaux pression PVC selon norme DIN 8061/62, équivalent SASO 14-15 (métrique).',
        features: ['DIN 8061/62 & SASO 14-15 certified', 'PN 4/6/10/16 classes', 'GCC & Saudi market standard', 'Chemical resistant PVC-U', 'ISO 9001:2015 production'],
        featuresAr: ['معتمدة وفق DIN 8061/62 و SASO 14-15', 'فئات PN 4/6/10/16', 'معيار أسواق الخليج والسعودية', 'PVC-U مقاوم كيميائياً', 'إنتاج معتمد ISO 9001:2015'],
        featuresFr: ['Certifié DIN 8061/62 & SASO 14-15', 'Classes PN 4/6/10/16', 'Norme marchés du Golfe et Arabie Saoudite', 'PVC-U résistant chimiquement', 'Production certifiée ISO 9001:2015'],
        image: '/images/products/cover/pvc high pressure/CROWN PLASTIC PVC HIGH PRESSURE PIPE DIN 8061.png',
      },
      {
        slug: 'pvc-hp-pipes-bs-en-iso-1452-2',
        name: 'PVC High Pressure Pipes BS EN ISO 1452-2: 2009 (Inch)',
        nameAr: 'أنابيب الضغط العالي PVC وفق BS EN ISO 1452-2: 2009 (إنش)',
        nameFr: 'Tuyaux Haute Pression PVC BS EN ISO 1452-2: 2009 (Pouces)',
        shortLabel: 'BS EN ISO 1452-2',
        shortLabelAr: 'BS EN ISO 1452-2',
        shortLabelFr: 'BS EN ISO 1452-2',
        standards: ['BS EN ISO 1452-2:2009'],
        shortDescription: 'PVC pressure pipes to BS EN ISO 1452-2:2009 standard (imperial).',
        shortDescriptionAr: 'أنابيب ضغط PVC وفق معيار BS EN ISO 1452-2:2009 (إنش).',
        shortDescriptionFr: 'Tuyaux pression PVC selon norme BS EN ISO 1452-2:2009 (impérial).',
        features: ['BS EN ISO 1452-2:2009 certified', 'Imperial sizes ½″–12″', 'PN 9/12/15 pressure classes', 'Dubai Municipality approved', 'Potable water rated'],
        featuresAr: ['معتمدة وفق BS EN ISO 1452-2:2009', 'مقاسات إنشية ½″–12″', 'فئات ضغط PN 9/12/15', 'معتمدة من بلدية دبي', 'مصنفة لمياه الشرب'],
        featuresFr: ['Certifié BS EN ISO 1452-2:2009', 'Diamètres impériaux ½″–12″', 'Classes de pression PN 9/12/15', 'Approuvé Municipalité de Dubaï', 'Classement eau potable'],
        image: '/images/products/cover/pvc high pressure/CROWN PLASTIC PVC HIGH PRESSURE PIPE BS EN ISO 1452-22009.png',
      },
      {
        slug: 'pvc-hp-pipes-bs-3505',
        name: 'PVC High Pressure Pipes BS 3505:1986 For Cold Potable Water (Inch)',
        nameAr: 'أنابيب الضغط العالي PVC وفق BS 3505:1986 لمياه الشرب الباردة (إنش)',
        nameFr: 'Tuyaux Haute Pression PVC BS 3505:1986 Pour Eau Potable Froide (Pouces)',
        shortLabel: 'BS 3505:1986',
        shortLabelAr: 'BS 3505:1986',
        shortLabelFr: 'BS 3505:1986',
        standards: ['BS 3505:1986'],
        shortDescription: 'PVC pressure pipes to BS 3505:1986 for cold potable water supply (imperial).',
        shortDescriptionAr: 'أنابيب ضغط PVC وفق BS 3505:1986 لإمدادات مياه الشرب الباردة (إنش).',
        shortDescriptionFr: 'Tuyaux pression PVC selon BS 3505:1986 pour adduction d\'eau potable froide (impérial).',
        features: ['BS 3505:1986 — potable water approved', 'Imperial sizes ½″–12″', 'Classes up to PN 15', 'Hygiene & safety certified', 'UAE water authority compliant'],
        featuresAr: ['BS 3505:1986 — معتمدة لمياه الشرب', 'مقاسات إنشية ½″–12″', 'فئات حتى PN 15', 'معتمدة للنظافة والسلامة', 'متوافقة مع هيئات المياه الإماراتية'],
        featuresFr: ['BS 3505:1986 — approuvé eau potable', 'Diamètres impériaux ½″–12″', 'Classes jusqu\'à PN 15', 'Certifié hygiène et sécurité', 'Conforme aux autorités de l\'eau EAU'],
        image: '/images/products/cover/pvc high pressure/CROWN PLASTIC PVC HIGH PRESSURE PIPE BS 35051986.png',
      },
      {
        slug: 'pvc-hp-pipes-bs-3506',
        name: 'PVC High Pressure Pipes BS 3506:1969 For Industrial Uses (Inch)',
        nameAr: 'أنابيب الضغط العالي PVC وفق BS 3506:1969 للاستخدامات الصناعية (إنش)',
        nameFr: 'Tuyaux Haute Pression PVC BS 3506:1969 Pour Usage Industriel (Pouces)',
        shortLabel: 'BS 3506:1969',
        shortLabelAr: 'BS 3506:1969',
        shortLabelFr: 'BS 3506:1969',
        standards: ['BS 3506:1969'],
        shortDescription: 'PVC pressure pipes to BS 3506:1969 for industrial applications (imperial).',
        shortDescriptionAr: 'أنابيب ضغط PVC وفق BS 3506:1969 للتطبيقات الصناعية (إنش).',
        shortDescriptionFr: 'Tuyaux pression PVC selon BS 3506:1969 pour applications industrielles (impérial).',
        features: ['BS 3506:1969 — industrial grade', 'Imperial sizes ½″–12″', 'Chemical processing rated', 'Classes up to PN 15', 'JAFZA/KIZAD industrial zones'],
        featuresAr: ['BS 3506:1969 — درجة صناعية', 'مقاسات إنشية ½″–12″', 'مصنفة للمعالجة الكيميائية', 'فئات حتى PN 15', 'المناطق الصناعية جافزا/كيزاد'],
        featuresFr: ['BS 3506:1969 — grade industriel', 'Diamètres impériaux ½″–12″', 'Classement process chimique', 'Classes jusqu\'à PN 15', 'Zones industrielles JAFZA/KIZAD'],
        image: '/images/products/cover/pvc high pressure/CROWN PLASTIC PVC HIGH PRESSURE PIPE BS 35061969.png',
      },
      {
        slug: 'pvc-hp-pipes-astm-d1785',
        name: 'PVC High Pressure Pipes ASTM D 1785 SCH40 / SCH 80 (Inch)',
        nameAr: 'أنابيب الضغط العالي PVC وفق ASTM D 1785 جدول 40 / جدول 80 (إنش)',
        nameFr: 'Tuyaux Haute Pression PVC ASTM D 1785 SCH40 / SCH 80 (Pouces)',
        shortLabel: 'ASTM D 1785',
        shortLabelAr: 'ASTM D 1785',
        shortLabelFr: 'ASTM D 1785',
        standards: ['ASTM D 1785', 'SCH 40', 'SCH 80'],
        shortDescription: 'PVC pressure pipes to ASTM D 1785 Schedule 40/80 (imperial).',
        shortDescriptionAr: 'أنابيب ضغط PVC وفق ASTM D 1785 جدول 40/80 (إنش).',
        shortDescriptionFr: 'Tuyaux pression PVC selon ASTM D 1785 Schedule 40/80 (impérial).',
        features: ['ASTM D 1785 certified', 'Schedule 40 & Schedule 80', 'Up to 58.6 bar pressure', 'American-spec projects', 'Oil & gas auxiliary systems'],
        featuresAr: ['معتمدة وفق ASTM D 1785', 'جدول 40 وجدول 80', 'ضغط يصل إلى 58.6 بار', 'مشاريع المواصفات الأمريكية', 'الأنظمة المساعدة للنفط والغاز'],
        featuresFr: ['Certifié ASTM D 1785', 'Schedule 40 & Schedule 80', 'Pression jusqu\'à 58,6 bar', 'Projets aux normes américaines', 'Systèmes auxiliaires pétrole et gaz'],
        image: '/images/products/cover/pvc high pressure/CROWN PLASTIC PVC HIGH PRESSURE PIPE ASTM D 1785.png',
      },
      {
        slug: 'pvc-hp-pipes-astm-d2241',
        name: 'PVC High Pressure Pipes ASTM D 2241 (Inch)',
        nameAr: 'أنابيب الضغط العالي PVC وفق ASTM D 2241 (إنش)',
        nameFr: 'Tuyaux Haute Pression PVC ASTM D 2241 (Pouces)',
        shortLabel: 'ASTM D 2241',
        shortLabelAr: 'ASTM D 2241',
        shortLabelFr: 'ASTM D 2241',
        standards: ['ASTM D 2241'],
        shortDescription: 'PVC pressure pipes to ASTM D 2241 standard (imperial).',
        shortDescriptionAr: 'أنابيب ضغط PVC وفق معيار ASTM D 2241 (إنش).',
        shortDescriptionFr: 'Tuyaux pression PVC selon norme ASTM D 2241 (impérial).',
        features: ['ASTM D 2241 certified', 'SDR-rated pressure classes', 'Cost-effective wall optimisation', 'Imperial sizes', 'UAE contractor preferred'],
        featuresAr: ['معتمدة وفق ASTM D 2241', 'فئات ضغط مصنفة SDR', 'تحسين اقتصادي لسماكة الجدار', 'مقاسات إنشية', 'مفضلة لدى مقاولي الإمارات'],
        featuresFr: ['Certifié ASTM D 2241', 'Classes de pression SDR', 'Optimisation économique de l\'épaisseur de paroi', 'Diamètres impériaux', 'Privilégié par les entrepreneurs EAU'],
        image: '/images/products/cover/pvc high pressure/CROWN PLASTIC PVC HIGH PRESSURE PIPE ASTM D 2241.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 4) PVC HIGH PRESSURE FITTINGS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'pvc-high-pressure-fittings',
    name: 'PVC High Pressure Fittings',
    nameAr: 'وصلات الضغط العالي PVC',
    nameFr: 'Raccords Haute Pression PVC',
    shortDescription: 'DM-approved high pressure Pipes / Fittings to DIN 8063 and BS EN 1452:3/BS 4346 (PN 15), including valves. Factory burst-tested to 25.0 MPa. Wall thickness tolerance ±0.3 mm ensures leak-free joints under thermal cycling at 0.06 mm/m·K expansion. Supplied across Dubai Creek Harbour and Aljada Community water distribution networks.',
    shortDescriptionAr: 'وصلات ضغط عالي معتمدة من بلدية دبي وفق DIN 8063 و BS EN 1452:3/BS 4346 (PN 15) بما في ذلك الصمامات. مختبرة بضغط انفجار 25.0 ميجاباسكال. تفاوت سمك الجدار ±0.3 مم يضمن وصلات بدون تسريب تحت الدورات الحرارية بمعامل تمدد 0.06 مم/م·كلفن. تم التوريد لشبكات توزيع المياه في دبي كريك هاربور ومجتمع الجادة.',
    shortDescriptionFr: 'Raccords haute pression approuvés par la Municipalité de Dubaï selon DIN 8063 et BS EN 1452:3/BS 4346 (PN 15), incluant vannes. Testés en éclatement à 25,0 MPa. Tolérance d\'épaisseur de paroi ±0,3 mm garantissant des joints étanches sous cycles thermiques (coefficient de dilatation 0,06 mm/m·K). Fournis pour les réseaux de distribution d\'eau de Dubai Creek Harbour et Aljada Community.',
    icon: '💧',
    image: '/images/products/sub_products/PVC.jpg',
    subProducts: [
      {
        slug: 'pvc-hp-fittings-din-8063',
        name: 'PVC High Pressure Fittings DIN 8063',
        nameAr: 'وصلات الضغط العالي PVC وفق DIN 8063',
        nameFr: 'Raccords Haute Pression PVC DIN 8063',
        shortLabel: 'DIN 8063',
        shortLabelAr: 'DIN 8063',
        shortLabelFr: 'DIN 8063',
        standards: ['DIN 8063'],
        shortDescription: 'PVC high pressure fittings to DIN 8063 standard.',
        shortDescriptionAr: 'وصلات ضغط عالي PVC وفق معيار DIN 8063.',
        shortDescriptionFr: 'Raccords haute pression PVC selon norme DIN 8063.',
        features: ['DIN 8063 certified', 'PN 10/16 rated', 'Metric 20–200 mm', 'UAE contractor preferred', 'ISO 9001:2015 production'],
        featuresAr: ['معتمدة وفق DIN 8063', 'مصنفة PN 10/16', 'متري 20–200 مم', 'مفضلة لدى مقاولي الإمارات', 'إنتاج ISO 9001:2015'],
        featuresFr: ['Certifié DIN 8063', 'Classement PN 10/16', 'Métrique 20–200 mm', 'Privilégié par les entrepreneurs EAU', 'Production ISO 9001:2015'],
        image: '/images/products/cover/pvc high pressure/fittings/DIN 8063.png',
      },
      {
        slug: 'pvc-hp-fittings-bs-en-1452-3',
        name: 'PVC High Pressure Fittings BS EN 1452:3/BS 4346 (PN 15)',
        nameAr: 'وصلات الضغط العالي PVC وفق BS EN 1452:3/BS 4346 (PN 15)',
        nameFr: 'Raccords Haute Pression PVC BS EN 1452:3/BS 4346 (PN 15)',
        shortLabel: 'BS EN 1452:3 / BS 4346',
        shortLabelAr: 'BS EN 1452:3 / BS 4346',
        shortLabelFr: 'BS EN 1452:3 / BS 4346',
        standards: ['BS EN 1452:3', 'BS 4346', 'PN 15'],
        shortDescription: 'PVC high pressure fittings to BS EN 1452:3/BS 4346 (PN 15) standard.',
        shortDescriptionAr: 'وصلات ضغط عالي PVC وفق معيار BS EN 1452:3/BS 4346 (PN 15).',
        shortDescriptionFr: 'Raccords haute pression PVC selon BS EN 1452:3/BS 4346 (PN 15).',
        features: ['BS EN 1452:3 / BS 4346 certified', 'Class E / PN 15 rated', 'Imperial ½″–8″', 'Dubai Municipality approved', 'Flanges & hex nipples'],
        featuresAr: ['معتمدة BS EN 1452:3 / BS 4346', 'مصنفة فئة E / PN 15', 'إنشي ½″–8″', 'معتمدة من بلدية دبي', 'فلنجات ونيبلات سداسية'],
        featuresFr: ['Certifié BS EN 1452:3 / BS 4346', 'Classement Classe E / PN 15', 'Impérial ½″–8″', 'Approuvé Municipalité de Dubaï', 'Brides et mamelons hexagonaux'],
        image: '/images/products/cover/pvc high pressure/fittings/BS EN 14523BS 4346 PN 15.png',
      },
      {
        slug: 'pvc-hp-fittings-valves',
        name: 'PVC High Pressure Valves',
        nameAr: 'صمامات الضغط العالي PVC',
        nameFr: 'Vannes Haute Pression PVC',
        shortLabel: 'Valves',
        shortLabelAr: 'صمامات',
        shortLabelFr: 'Vannes',
        standards: ['Crown Specification'],
        shortDescription: 'PVC high pressure valves for flow control applications.',
        shortDescriptionAr: 'صمامات ضغط عالي PVC للتحكم في التدفق.',
        shortDescriptionFr: 'Vannes haute pression PVC pour applications de contrôle de débit.',
        features: ['True union & compact ball valves', 'Precision flow control', 'UV resistant for Gulf climate', 'Metric & imperial sizes', 'ISO 9001:2015 UAE facility'],
        featuresAr: ['صمامات اتحاد حقيقي وكرة مدمجة', 'تحكم دقيق بالتدفق', 'مقاومة UV لمناخ الخليج', 'مقاسات مترية وإنشية', 'منشأة ISO 9001:2015 بالإمارات'],
        featuresFr: ['Vannes à union et à bille compactes', 'Contrôle de débit de précision', 'Résistant UV pour climat du Golfe', 'Diamètres métriques et impériaux', 'Installation certifiée ISO 9001:2015 aux EAU'],
        image: '/images/products/cover/pvc high pressure/fittings/valves.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 5) PVC SCH 40 FITTINGS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'pvc-sch-40-fittings',
    name: 'PVC SCH 40 Fittings',
    nameAr: 'وصلات PVC جدول 40',
    nameFr: 'Raccords PVC SCH 40',
    shortDescription: 'ASTM D 2466 Schedule 40 pressure Pipes / Fittings for UAE pool, irrigation, and industrial systems. Burst-tested to 22.0 MPa with ±0.3 mm dimensional tolerance. Derating factor 0.50 at 50°C maintains structural margins for exposed Gulf installations. Certification ref: DM-SCH40-ASTMD2466-2024-001.',
    shortDescriptionAr: 'وصلات ضغط جدول 40 وفق ASTM D 2466 لأنظمة المسابح والري والصناعة في الإمارات. مختبرة بضغط انفجار 22.0 ميجاباسكال بتفاوت أبعاد ±0.3 مم. معامل تخفيض 0.50 عند 50°C يحافظ على هوامش السلامة الهيكلية للتركيبات المكشوفة في الخليج. رقم الشهادة: DM-SCH40-ASTMD2466-2024-001.',
    shortDescriptionFr: 'Raccords pression Schedule 40 selon ASTM D 2466 pour systèmes de piscines, irrigation et industrie aux EAU. Testés en éclatement à 22,0 MPa avec tolérance dimensionnelle ±0,3 mm. Facteur de déclassement 0,50 à 50 °C maintenant les marges de sécurité structurelle pour installations exposées dans le Golfe. Réf. certification : DM-SCH40-ASTMD2466-2024-001.',
    icon: '🔩',
    image: '/images/products/cover/pvc high pressure/fittings/PVC SCH 40 Fittings.png',
    subProducts: [
      {
        slug: 'pvc-sch-40-fittings-astm-d2466',
        name: 'PVC SCH 40 Fittings ASTM D 2466',
        nameAr: 'وصلات PVC جدول 40 وفق ASTM D 2466',
        nameFr: 'Raccords PVC SCH 40 ASTM D 2466',
        shortLabel: 'ASTM D 2466',
        shortLabelAr: 'ASTM D 2466',
        shortLabelFr: 'ASTM D 2466',
        standards: ['ASTM D 2466', 'SCH 40'],
        shortDescription: 'PVC Schedule 40 fittings to ASTM D 2466 standard.',
        shortDescriptionAr: 'وصلات PVC جدول 40 وفق معيار ASTM D 2466.',
        shortDescriptionFr: 'Raccords PVC Schedule 40 selon norme ASTM D 2466.',
        features: ['ASTM D 2466 certified', 'SCH 40 pressure rated', 'Imperial ½″–8″', 'Pool & irrigation specialist', 'ISO 9001:2015 UAE facility'],
        featuresAr: ['معتمدة ASTM D 2466', 'مصنفة ضغط SCH 40', 'إنشي ½″–8″', 'متخصصة بالمسابح والري', 'منشأة ISO 9001:2015 بالإمارات'],
        featuresFr: ['Certifié ASTM D 2466', 'Classement pression SCH 40', 'Impérial ½″–8″', 'Spécialiste piscines et irrigation', 'Installation certifiée ISO 9001:2015 aux EAU'],
        image: '/images/products/cover/pvc high pressure/fittings/PVC SCH 40 Fittings.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 6) PVC DUCT PIPES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'pvc-duct-pipes',
    name: 'PVC Duct Pipes',
    nameAr: 'أنابيب مجاري PVC',
    nameFr: 'Tuyaux de Gaines PVC',
    shortDescription: 'Etisalat, DU, and DEWA-approved PVC Duct Pipes / Fittings to NEMA TC 2, NEMA TC 6 & 8, DIN 8062, and BS 3505/06. Wall tolerance ±0.2 mm. Vicat softening at 79°C prevents conduit deformation under Gulf asphalt temperatures. Deployed on DEWA Smart Grid project: 35,000 LM of NEMA TC 2 underground cable protection.',
    shortDescriptionAr: 'أنابيب / تجهيزات مجاري PVC معتمدة من اتصالات ودو وديوا وفق NEMA TC 2 و NEMA TC 6 و 8 و DIN 8062 و BS 3505/06. تفاوت سمك الجدار ±0.2 مم. تليين فيكات عند 79°C يمنع تشوه القنوات تحت درجات حرارة الأسفلت في الخليج. تم التوريد لمشروع ديوا سمارت غريد: 35,000 متر طولي من حماية الكابلات تحت الأرض NEMA TC 2.',
    shortDescriptionFr: 'Tuyaux / Raccords de gaines PVC approuvés Etisalat, DU et DEWA selon NEMA TC 2, NEMA TC 6 & 8, DIN 8062 et BS 3505/06. Tolérance de paroi ±0,2 mm. Ramollissement Vicat à 79 °C empêchant la déformation des conduits sous les températures d\'asphalte du Golfe. Déployés sur le projet DEWA Smart Grid : 35 000 ML de protection de câbles souterrains NEMA TC 2.',
    icon: '⚡',
    image: '/images/products/sub_products/upvc-duct-orange.jpg',
    subProducts: [
      {
        slug: 'pvc-duct-pipes-nema-tc-2',
        name: 'PVC Duct Pipes NEMA TC 2: 2003',
        nameAr: 'أنابيب مجاري PVC وفق NEMA TC 2: 2003',
        nameFr: 'Tuyaux de Gaines PVC NEMA TC 2: 2003',
        shortLabel: 'NEMA TC 2',
        shortLabelAr: 'NEMA TC 2',
        shortLabelFr: 'NEMA TC 2',
        standards: ['NEMA TC 2:2003'],
        shortDescription: 'PVC Duct pipes to NEMA TC 2:2003 standard for electrical cable ducting.',
        shortDescriptionAr: 'أنابيب مجاري PVC وفق معيار NEMA TC 2:2003 لمجاري الكابلات الكهربائية.',
        shortDescriptionFr: 'Tuyaux de gaines PVC selon norme NEMA TC 2:2003 pour conduits de câbles électriques.',
        features: ['NEMA TC 2:2003 certified', 'EPC 40 & EPC 80 grades', 'Imperial ½″–8″', 'Cable duct specialist', 'ISO 9001:2015 UAE facility'],
        featuresAr: ['معتمدة NEMA TC 2:2003', 'درجات EPC 40 و EPC 80', 'إنشي ½″–8″', 'متخصصة بمجاري الكابلات', 'منشأة ISO 9001:2015 بالإمارات'],
        featuresFr: ['Certifié NEMA TC 2:2003', 'Grades EPC 40 & EPC 80', 'Impérial ½″–8″', 'Spécialiste gaines de câbles', 'Installation certifiée ISO 9001:2015 aux EAU'],
        image: '/images/products/cover/upvs duct/pipes/CROWN PLASTIC PVC DUCT PIPE NEMA TC 22003.png',
      },
      {
        slug: 'pvc-duct-pipes-nema-tc-6-8',
        name: 'PVC Duct Pipes NEMA TC 6 & 8/ASTM F 512',
        nameAr: 'أنابيب مجاري PVC وفق NEMA TC 6 و 8/ASTM F 512',
        nameFr: 'Tuyaux de Gaines PVC NEMA TC 6 & 8/ASTM F 512',
        shortLabel: 'NEMA TC 6 & 8',
        shortLabelAr: 'NEMA TC 6 و 8',
        shortLabelFr: 'NEMA TC 6 & 8',
        standards: ['NEMA TC 6', 'NEMA TC 8', 'ASTM F 512'],
        shortDescription: 'PVC Duct pipes to NEMA TC 6 & 8/ASTM F 512 standard.',
        shortDescriptionAr: 'أنابيب مجاري PVC وفق معيار NEMA TC 6 و 8/ASTM F 512.',
        shortDescriptionFr: 'Tuyaux de gaines PVC selon norme NEMA TC 6 & 8/ASTM F 512.',
        features: ['NEMA TC 6 & 8 / ASTM F 512', 'EB & DB burial rated', 'Imperial 1″–6″', 'Direct & encased burial', 'GCC infrastructure approved'],
        featuresAr: ['NEMA TC 6 و 8 / ASTM F 512', 'مصنفة للدفن EB و DB', 'إنشي 1″–6″', 'دفن مباشر ومغلف', 'معتمدة للبنية التحتية بالخليج'],
        featuresFr: ['NEMA TC 6 & 8 / ASTM F 512', 'Classement enfouissement EB & DB', 'Impérial 1″–6″', 'Enfouissement direct et enrobé', 'Approuvé infrastructure du Golfe'],
        image: '/images/products/cover/upvs duct/pipes/CROWN PLASTIC PVC DUCT PIPE ASTM F512.png',
      },
      {
        slug: 'pvc-duct-pipes-din-8062',
        name: 'PVC Duct Pipes DIN 8062',
        nameAr: 'أنابيب مجاري PVC وفق DIN 8062',
        nameFr: 'Tuyaux de Gaines PVC DIN 8062',
        shortLabel: 'DIN 8062',
        shortLabelAr: 'DIN 8062',
        shortLabelFr: 'DIN 8062',
        standards: ['DIN 8062'],
        shortDescription: 'PVC Duct pipes to DIN 8062 standard.',
        shortDescriptionAr: 'أنابيب مجاري PVC وفق معيار DIN 8062.',
        shortDescriptionFr: 'Tuyaux de gaines PVC selon norme DIN 8062.',
        features: ['DIN 8062 certified', 'PN 4 to PN 16 classes', 'Metric 20–315 mm', 'Multi-pressure rated', 'UAE manufactured'],
        featuresAr: ['معتمدة DIN 8062', 'فئات PN 4 إلى PN 16', 'متري 20–315 مم', 'متعددة تصنيفات الضغط', 'مصنعة في الإمارات'],
        featuresFr: ['Certifié DIN 8062', 'Classes PN 4 à PN 16', 'Métrique 20–315 mm', 'Multi-classement pression', 'Fabriqué aux EAU'],
        image: '/images/products/cover/upvs duct/pipes/CROWN PLASTIC PVC DUCT PIPE DIN 8062.png',
      },
      {
        slug: 'pvc-duct-pipes-etisalat-du',
        name: 'PVC Duct Pipes For Etisalat & DU',
        nameAr: 'أنابيب مجاري PVC لاتصالات ودو',
        nameFr: 'Tuyaux de Gaines PVC Pour Etisalat & DU',
        shortLabel: 'Etisalat & DU',
        shortLabelAr: 'اتصالات ودو',
        shortLabelFr: 'Etisalat & DU',
        standards: ['Etisalat Approved', 'DU Approved'],
        shortDescription: 'PVC Duct pipes approved for Etisalat and DU telecom infrastructure.',
        shortDescriptionAr: 'أنابيب مجاري PVC معتمدة للبنية التحتية لاتصالات ودو.',
        shortDescriptionFr: 'Tuyaux de gaines PVC approuvés pour l\'infrastructure télécom Etisalat et DU.',
        features: ['Etisalat & DU approved', 'D54/D56/D57 specifications', 'UAE telecom standard', 'Underground cable protection', 'Crown Plastic certified'],
        featuresAr: ['معتمدة من اتصالات ودو', 'مواصفات D54/D56/D57', 'معيار اتصالات الإمارات', 'حماية كابلات تحت الأرض', 'معتمدة من كراون بلاستيك'],
        featuresFr: ['Approuvé Etisalat & DU', 'Spécifications D54/D56/D57', 'Norme télécom EAU', 'Protection câbles souterrains', 'Certifié Crown Plastic'],
        image: '/images/products/cover/upvs duct/pipes/CROWN PLASTIC PVC DUCT PIPEetisalat&du.png',
      },
      {
        slug: 'pvc-duct-pipes-bs-3505-06',
        name: 'PVC Duct Pipes BS 3505/06',
        nameAr: 'أنابيب مجاري PVC وفق BS 3505/06',
        nameFr: 'Tuyaux de Gaines PVC BS 3505/06',
        shortLabel: 'BS 3505/06',
        shortLabelAr: 'BS 3505/06',
        shortLabelFr: 'BS 3505/06',
        standards: ['BS 3505', 'BS 3506'],
        shortDescription: 'PVC Duct pipes to BS 3505/06 standard.',
        shortDescriptionAr: 'أنابيب مجاري PVC وفق معيار BS 3505/06.',
        shortDescriptionFr: 'Tuyaux de gaines PVC selon norme BS 3505/06.',
        features: ['BS 3505/06 certified', 'PN 6 to PN 15 classes', 'Imperial ½″–12″', 'Class-O to Class-E', 'Dubai contractor preferred'],
        featuresAr: ['معتمدة BS 3505/06', 'فئات PN 6 إلى PN 15', 'إنشي ½″–12″', 'Class-O إلى Class-E', 'مفضلة لدى مقاولي دبي'],
        featuresFr: ['Certifié BS 3505/06', 'Classes PN 6 à PN 15', 'Impérial ½″–12″', 'Class-O à Class-E', 'Privilégié par les entrepreneurs de Dubaï'],
        image: '/images/products/cover/upvs duct/pipes/CROWN PLASTIC PVC DUCT PIPE BS 3505.png',
      },
      {
        slug: 'pvc-duct-pipes-non-standard',
        name: 'PVC Duct Non-Standard Pipes',
        nameAr: 'أنابيب مجاري PVC غير القياسية',
        nameFr: 'Tuyaux de Gaines PVC Non Standard',
        shortLabel: 'Non-Standard',
        shortLabelAr: 'غير قياسية',
        shortLabelFr: 'Non Standard',
        standards: ['Crown Specification'],
        shortDescription: 'Non-standard PVC Duct pipes for specialized project requirements.',
        shortDescriptionAr: 'أنابيب مجاري PVC غير قياسية لمتطلبات المشاريع المتخصصة.',
        shortDescriptionFr: 'Tuyaux de gaines PVC hors normes pour exigences de projets spécialisés.',
        features: ['Custom sizes 75–160 mm', 'Specialized project specs', 'Crown Specification', 'UAE manufactured', 'Flexible wall thickness'],
        featuresAr: ['مقاسات مخصصة 75–160 مم', 'مواصفات مشاريع متخصصة', 'مواصفات كراون', 'مصنعة في الإمارات', 'سمك جدار مرن'],
        featuresFr: ['Dimensions personnalisées 75–160 mm', 'Spécifications projets spécialisés', 'Spécification Crown', 'Fabriqué aux EAU', 'Épaisseur de paroi flexible'],
        image: '/images/products/cover/upvs duct/pipes/CROWN PLASTIC PVC DUCT PIPEnonstandard.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 7) PVC DUCT FITTINGS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'pvc-duct-fittings',
    name: 'PVC Duct Fittings',
    nameAr: 'وصلات مجاري PVC',
    nameFr: 'Raccords de Gaines PVC',
    shortDescription: 'Etisalat and DU-compliant duct Pipes / Fittings for underground cable protection systems. Wall tolerance ±0.3 mm. Derating factor 0.55 at Gulf peak temperatures sustains conduit crush resistance. Certified under DM-DUCT-FIT-2024-001.',
    shortDescriptionAr: 'وصلات مجاري متوافقة مع اتصالات ودو لأنظمة حماية الكابلات تحت الأرض. تفاوت سمك الجدار ±0.3 مم. معامل تخفيض 0.55 عند ذروة حرارة الخليج يحافظ على مقاومة القنوات للسحق. معتمدة تحت رقم DM-DUCT-FIT-2024-001.',
    shortDescriptionFr: 'Raccords de gaines conformes Etisalat et DU pour systèmes de protection de câbles souterrains. Tolérance de paroi ±0,3 mm. Facteur de déclassement 0,55 aux pics de température du Golfe maintenant la résistance à l\'écrasement. Certifié sous réf. DM-DUCT-FIT-2024-001.',
    icon: '⚡',
    image: '/images/products/cover/upvs duct/fittings/duct-socketa.png',
    subProducts: [
      {
        slug: 'pvc-duct-fittings-standard',
        name: 'PVC Duct Fittings',
        nameAr: 'وصلات مجاري PVC',
        nameFr: 'Raccords de Gaines PVC',
        shortLabel: 'Duct Fittings',
        shortLabelAr: 'وصلات المجاري',
        shortLabelFr: 'Raccords de Gaines',
        standards: ['Crown Specification'],
        shortDescription: 'PVC Duct fittings for underground cable protection systems.',
        shortDescriptionAr: 'وصلات مجاري PVC لأنظمة حماية الكابلات تحت الأرض.',
        shortDescriptionFr: 'Raccords de gaines PVC pour systèmes de protection de câbles souterrains.',
        features: ['Etisalat & DU compliant', 'End caps, sockets, bellmouths', 'LR bends for street lighting', 'Corrosion resistant for UAE soil', 'Watertight solvent-welded joints'],
        featuresAr: ['متوافقة مع اتصالات ودو', 'أغطية ومقابس وأبواق', 'انحناءات LR لإنارة الشوارع', 'مقاومة تآكل لتربة الإمارات', 'وصلات لحام بالمذيب مانعة للتسرب'],
        featuresFr: ['Conforme Etisalat & DU', 'Bouchons, manchons, évases', 'Coudes LR pour éclairage public', 'Résistant à la corrosion du sol des EAU', 'Joints soudés au solvant étanches'],
        image: '/images/products/cover/upvs duct/fittings/duct-socketa.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 8) PVC CONDUIT PIPES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'pvc-conduit-pipes',
    name: 'PVC Conduit Pipes',
    nameAr: 'أنابيب القنوات PVC',
    nameFr: 'Tubes de Conduits PVC',
    shortDescription: 'Civil Defense and DEWA-approved electrical conduit Pipes / Fittings: 1250N / 750N / 320N compression force grades plus SCH 40 and SCH 80. Wall tolerance ±0.2 mm. Vicat softening at 79°C prevents conduit collapse in exposed rooftop and riser installations. Supplied to SEWA Sharjah: 22,000 LM for street lighting conduit upgrade.',
    shortDescriptionAr: 'أنابيب / تجهيزات قنوات كهربائية معتمدة من الدفاع المدني وديوا: درجات قوة ضغط 1250N / 750N / 320N بالإضافة إلى جدول 40 وجدول 80. تفاوت سمك الجدار ±0.2 مم. تليين فيكات عند 79°C يمنع انهيار القنوات في التركيبات المكشوفة على الأسطح والمواسير الرأسية. تم التوريد لسيوا الشارقة: 22,000 متر طولي لترقية قنوات إنارة الشوارع.',
    shortDescriptionFr: 'Tubes / Raccords de conduits électriques approuvés Défense Civile et DEWA : grades de force de compression 1250N / 750N / 320N plus SCH 40 et SCH 80. Tolérance de paroi ±0,2 mm. Ramollissement Vicat à 79 °C empêchant l\'effondrement des conduits dans les installations exposées en toiture et colonnes montantes. Fournis à SEWA Sharjah : 22 000 ML pour mise à niveau des conduits d\'éclairage public.',
    icon: '🔌',
    image: '/images/products/sub_products/upvc-conduit-sch-40.jpg',
    subProducts: [
      {
        slug: 'pvc-conduit-pipes-compression-force',
        name: 'PVC Conduit Pipes 1250N / 750N / 320N Compression Force',
        nameAr: 'أنابيب القنوات PVC بقوة ضغط 1250N / 750N / 320N',
        nameFr: 'Tubes de Conduits PVC 1250N / 750N / 320N Force de Compression',
        shortLabel: '1250N / 750N / 320N',
        shortLabelAr: '1250N / 750N / 320N',
        shortLabelFr: '1250N / 750N / 320N',
        standards: ['1250N', '750N', '320N'],
        shortDescription: 'PVC Conduit pipes rated at 1250N, 750N, and 320N compression force.',
        shortDescriptionAr: 'أنابيب قنوات PVC بتصنيف 1250N و 750N و 320N لقوة الضغط.',
        shortDescriptionFr: 'Tubes de conduits PVC classés 1250N, 750N et 320N en force de compression.',
        features: ['1250N / 750N / 320N grades', 'Fire-retardant PVC-U', '20–50 mm sizes', 'MEP infrastructure specialist', 'ISO 9001:2015 UAE facility'],
        featuresAr: ['درجات 1250N / 750N / 320N', 'PVC-U مقاوم للحريق', 'مقاسات 20–50 مم', 'متخصصة بالبنية التحتية MEP', 'منشأة ISO 9001:2015 بالإمارات'],
        featuresFr: ['Grades 1250N / 750N / 320N', 'PVC-U auto-extinguible', 'Diamètres 20–50 mm', 'Spécialiste infrastructure MEP', 'Installation certifiée ISO 9001:2015 aux EAU'],
        image: '/images/products/cover/conduits/pipes/CROWN PLASTIC PVC CONDUIT PIPE 1250N.png',
      },
      {
        slug: 'pvc-conduit-pipes-sch-40',
        name: 'PVC Conduit Pipes SCH 40 CONDUIT- US',
        nameAr: 'أنابيب القنوات PVC جدول 40 - أمريكي',
        nameFr: 'Tubes de Conduits PVC SCH 40 - Norme US',
        shortLabel: 'SCH 40',
        shortLabelAr: 'جدول 40',
        shortLabelFr: 'SCH 40',
        standards: ['SCH 40', 'UL Listed'],
        shortDescription: 'Standard Schedule 40 PVC Conduit pipes for electrical installations (US standard).',
        shortDescriptionAr: 'أنابيب قنوات PVC جدول 40 القياسية للتمديدات الكهربائية (معيار أمريكي).',
        shortDescriptionFr: 'Tubes de conduits PVC Schedule 40 standard pour installations électriques (norme US).',
        features: ['US Schedule 40 standard', '½″–6″ trade sizes', 'Optimal wall thickness', 'General-purpose conduit', 'ISO 9001:2015 certified'],
        featuresAr: ['معيار جدول 40 الأمريكي', 'مقاسات تجارية ½″–6″', 'سمك جدار مثالي', 'قنوات للأغراض العامة', 'معتمدة ISO 9001:2015'],
        featuresFr: ['Norme Schedule 40 US', 'Tailles commerciales ½″–6″', 'Épaisseur de paroi optimale', 'Conduits usage général', 'Certifié ISO 9001:2015'],
        image: '/images/products/cover/conduits/pipes/CROWN PLASTIC PVC CONDUIT PIPE SCH 40.png',
      },
      {
        slug: 'pvc-conduit-pipes-sch-80',
        name: 'PVC Conduit Pipes SCH 80 CONDUIT- US',
        nameAr: 'أنابيب القنوات PVC جدول 80 - أمريكي',
        nameFr: 'Tubes de Conduits PVC SCH 80 - Norme US',
        shortLabel: 'SCH 80',
        shortLabelAr: 'جدول 80',
        shortLabelFr: 'SCH 80',
        standards: ['SCH 80', 'UL Listed'],
        shortDescription: 'Heavy-duty Schedule 80 PVC Conduit pipes for electrical installations (US standard).',
        shortDescriptionAr: 'أنابيب قنوات PVC جدول 80 للخدمة الشاقة للتمديدات الكهربائية (معيار أمريكي).',
        shortDescriptionFr: 'Tubes de conduits PVC Schedule 80 usage intensif pour installations électriques (norme US).',
        features: ['US Schedule 80 heavy-duty', '½″–6″ trade sizes', 'Enhanced wall thickness', 'High-traffic & industrial', 'ISO 9001:2015 certified'],
        featuresAr: ['جدول 80 الأمريكي شاق', 'مقاسات تجارية ½″–6″', 'سمك جدار محسّن', 'مناطق حركة عالية وصناعية', 'معتمدة ISO 9001:2015'],
        featuresFr: ['Schedule 80 US usage intensif', 'Tailles commerciales ½″–6″', 'Épaisseur de paroi renforcée', 'Zones à fort trafic et industrielles', 'Certifié ISO 9001:2015'],
        image: '/images/products/cover/conduits/pipes/CROWN PLASTIC PVC CONDUIT PIPE SCH 80.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 9) PP-R PIPES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'ppr-pipes',
    name: 'PP-R Pipes',
    nameAr: 'أنابيب PP-R',
    nameFr: 'Tuyaux PP-R',
    shortDescription: 'Dubai Municipality-compliant PP-R Pipes / Fittings to DIN 8077/78 in SDR11/PN10, SDR7.4/PN16, SDR6/PN20, and SDR5/PN25. Factory burst-tested to 35.0 MPa. Vicat softening at 152°C — operates continuously at 70°C with derating factor 0.80 at 50°C ambient. Deployed on JVC Residential Phase 2: 18,000 LM PN20 hot/cold risers across 480 units.',
    shortDescriptionAr: 'أنابيب / تجهيزات PP-R متوافقة مع بلدية دبي وفق DIN 8077/78 بتصنيفات SDR11/PN10 و SDR7.4/PN16 و SDR6/PN20 و SDR5/PN25. مختبرة بضغط انفجار 35.0 ميجاباسكال. تليين فيكات عند 152°C — تعمل باستمرار عند 70°C بمعامل تخفيض 0.80 عند حرارة محيطة 50°C. تم التوريد لمشروع JVC السكني المرحلة 2: 18,000 متر طولي PN20 مياه ساخنة/باردة عبر 480 وحدة.',
    shortDescriptionFr: 'Tuyaux / Raccords PP-R conformes à la Municipalité de Dubaï selon DIN 8077/78 en SDR11/PN10, SDR7.4/PN16, SDR6/PN20 et SDR5/PN25. Testés en éclatement à 35,0 MPa. Ramollissement Vicat à 152 °C — service continu à 70 °C avec facteur de déclassement 0,80 à 50 °C ambiant. Déployés sur JVC Résidentiel Phase 2 : 18 000 ML PN20 colonnes eau chaude/froide sur 480 unités.',
    icon: '🚿',
    image: '/images/products/sub_products/ppr-sdr11-pn10.jpg',
    subProducts: [
      {
        slug: 'ppr-pipes-sdr11-pn10',
        name: 'PP-R Pipes SDR11/PN10 DIN 8077/78',
        nameAr: 'أنابيب PP-R وفق SDR11/PN10 DIN 8077/78',
        nameFr: 'Tuyaux PP-R SDR11/PN10 DIN 8077/78',
        shortLabel: 'SDR11 / PN10',
        shortLabelAr: 'SDR11 / PN10',
        shortLabelFr: 'SDR11 / PN10',
        standards: ['DIN 8077', 'DIN 8078', 'PN 10', 'SDR11'],
        shortDescription: 'PP-R pipes with 10 bar pressure rating for cold water applications.',
        shortDescriptionAr: 'أنابيب PP-R بتصنيف ضغط 10 بار لتطبيقات المياه الباردة.',
        shortDescriptionFr: 'Tuyaux PP-R classés 10 bar pour applications eau froide.',
        features: ['SDR11 / PN10 rated', 'DIN 8077/78 certified', '20–110 mm', '50-year service life', 'Thermo-fusion welding'],
        featuresAr: ['مصنفة SDR11 / PN10', 'معتمدة DIN 8077/78', '20–110 مم', 'عمر خدمة 50 عاماً', 'لحام حراري'],
        featuresFr: ['Classement SDR11 / PN10', 'Certifié DIN 8077/78', '20–110 mm', 'Durée de vie 50 ans', 'Soudage par thermofusion'],
        image: '/images/products/cover/ppr/pipes/CROWN PLASTIC PPR PIPE SDR11 PN10.png',
      },
      {
        slug: 'ppr-pipes-sdr7-4-pn16',
        name: 'PP-R Pipes SDR7.4/PN16 DIN 8077/78',
        nameAr: 'أنابيب PP-R وفق SDR7.4/PN16 DIN 8077/78',
        nameFr: 'Tuyaux PP-R SDR7.4/PN16 DIN 8077/78',
        shortLabel: 'SDR7.4 / PN16',
        shortLabelAr: 'SDR7.4 / PN16',
        shortLabelFr: 'SDR7.4 / PN16',
        standards: ['DIN 8077', 'DIN 8078', 'PN 16', 'SDR7.4'],
        shortDescription: 'PP-R pipes with 16 bar pressure rating for hot and cold water systems.',
        shortDescriptionAr: 'أنابيب PP-R بتصنيف ضغط 16 بار لأنظمة المياه الساخنة والباردة.',
        shortDescriptionFr: 'Tuyaux PP-R classés 16 bar pour systèmes eau chaude et froide.',
        features: ['SDR7.4 / PN16 rated', 'Hot & cold water', 'DIN 8077/78 certified', '20–110 mm', 'HVAC compatible'],
        featuresAr: ['مصنفة SDR7.4 / PN16', 'مياه ساخنة وباردة', 'معتمدة DIN 8077/78', '20–110 مم', 'متوافقة مع HVAC'],
        featuresFr: ['Classement SDR7.4 / PN16', 'Eau chaude et froide', 'Certifié DIN 8077/78', '20–110 mm', 'Compatible HVAC'],
        image: '/images/products/cover/ppr/pipes/CROWN PLASTIC PPR PIPE SDR7.4 PN16.png',
      },
      {
        slug: 'ppr-pipes-sdr6-pn20',
        name: 'PP-R Pipes SDR6/PN20 DIN 8077/78',
        nameAr: 'أنابيب PP-R وفق SDR6/PN20 DIN 8077/78',
        nameFr: 'Tuyaux PP-R SDR6/PN20 DIN 8077/78',
        shortLabel: 'SDR6 / PN20',
        shortLabelAr: 'SDR6 / PN20',
        shortLabelFr: 'SDR6 / PN20',
        standards: ['DIN 8077', 'DIN 8078', 'PN 20', 'SDR6'],
        shortDescription: 'PP-R pipes with 20 bar pressure rating for demanding applications.',
        shortDescriptionAr: 'أنابيب PP-R بتصنيف ضغط 20 بار للتطبيقات المتطلبة.',
        shortDescriptionFr: 'Tuyaux PP-R classés 20 bar pour applications exigeantes.',
        features: ['SDR6 / PN20 high-pressure', 'Hot & cold 20 bar', 'DIN 8077/78 certified', '20–110 mm', 'Industrial grade'],
        featuresAr: ['ضغط عالي SDR6 / PN20', 'ساخن وبارد 20 بار', 'معتمدة DIN 8077/78', '20–110 مم', 'درجة صناعية'],
        featuresFr: ['Haute pression SDR6 / PN20', 'Eau chaude et froide 20 bar', 'Certifié DIN 8077/78', '20–110 mm', 'Grade industriel'],
        image: '/images/products/cover/ppr/pipes/CROWN PLASTIC PPR PIPE SDR11 PN20.png',
      },
      {
        slug: 'ppr-pipes-sdr5-pn25',
        name: 'PP-R Pipes SDR5/PN25 DIN 8077/78',
        nameAr: 'أنابيب PP-R وفق SDR5/PN25 DIN 8077/78',
        nameFr: 'Tuyaux PP-R SDR5/PN25 DIN 8077/78',
        shortLabel: 'SDR5 / PN25',
        shortLabelAr: 'SDR5 / PN25',
        shortLabelFr: 'SDR5 / PN25',
        standards: ['DIN 8077', 'DIN 8078', 'PN 25', 'SDR5'],
        shortDescription: 'PP-R pipes with 25 bar pressure rating for high-pressure applications.',
        shortDescriptionAr: 'أنابيب PP-R بتصنيف ضغط 25 بار لتطبيقات الضغط العالي.',
        shortDescriptionFr: 'Tuyaux PP-R classés 25 bar pour applications haute pression.',
        features: ['SDR5 / PN25 maximum pressure', '25 bar rated', 'DIN 8077/78 certified', 'Critical infrastructure', 'Contact for specs'],
        featuresAr: ['ضغط أقصى SDR5 / PN25', 'مصنفة 25 بار', 'معتمدة DIN 8077/78', 'بنية تحتية حرجة', 'تواصل للمواصفات'],
        featuresFr: ['Pression maximale SDR5 / PN25', 'Classement 25 bar', 'Certifié DIN 8077/78', 'Infrastructure critique', 'Contactez-nous pour les spécifications'],
        image: '/images/products/cover/ppr/pipes/CROWN PLASTIC PPR PIPE SDR5 PN25.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 10) HDPE PIPES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'hdpe-pipes',
    name: 'HDPE Pipes',
    nameAr: 'أنابيب HDPE',
    nameFr: 'Tuyaux HDPE',
    shortDescription: 'ADSSC and Abu Dhabi QCC-approved HDPE Pipes / Fittings in PE63, PE80, and PE100 grades to DIN 8072, ASAE S435, AUST STD 2698-1, and BS 1972/67. Burst-tested to 28.0 MPa with ±0.3 mm wall tolerance. Derating factor 0.63 at 50°C; Vicat softening at 127°C supports above-ground UV-stabilized runs. Deployed on KIZAD Industrial Zone: 28,000 LM of PE100 PN16 process water lines.',
    shortDescriptionAr: 'أنابيب / تجهيزات HDPE معتمدة من أدسك وهيئة جودة أبوظبي بدرجات PE63 و PE80 و PE100 وفق DIN 8072 و ASAE S435 و AUST STD 2698-1 و BS 1972/67. مختبرة بضغط انفجار 28.0 ميجاباسكال بتفاوت سمك جدار ±0.3 مم. معامل تخفيض 0.63 عند 50°C؛ تليين فيكات عند 127°C يدعم الخطوط المكشوفة المثبتة ضد الأشعة فوق البنفسجية. تم التوريد لمنطقة كيزاد الصناعية: 28,000 متر طولي من خطوط مياه العمليات PE100 PN16.',
    shortDescriptionFr: 'Tuyaux / Raccords HDPE approuvés ADSSC et QCC Abu Dhabi en grades PE63, PE80 et PE100 selon DIN 8072, ASAE S435, AUST STD 2698-1 et BS 1972/67. Testés en éclatement à 28,0 MPa avec tolérance de paroi ±0,3 mm. Facteur de déclassement 0,63 à 50 °C ; ramollissement Vicat à 127 °C supportant les lignes aériennes stabilisées UV. Déployés sur zone industrielle KIZAD : 28 000 ML de conduites d\'eau de process PE100 PN16.',
    icon: '🌊',
    image: '/images/products/sub_products/HDPE.jpg',
    subProducts: [
      {
        slug: 'hdpe-pipes-5mpa-pe63',
        name: 'HDPE Pipes 5 MPa (PE63)',
        nameAr: 'أنابيب HDPE بضغط 5 ميجاباسكال (PE63)',
        nameFr: 'Tuyaux HDPE 5 MPa (PE63)',
        shortLabel: '5 MPa (PE63)',
        shortLabelAr: '5 MPa (PE63)',
        shortLabelFr: '5 MPa (PE63)',
        standards: ['PE63', '5 MPa'],
        shortDescription: 'HDPE pipes rated at 5 MPa (PE63 grade).',
        shortDescriptionAr: 'أنابيب HDPE بتصنيف 5 ميجاباسكال (درجة PE63).',
        shortDescriptionFr: 'Tuyaux HDPE classés 5 MPa (grade PE63).',
        features: ['PE63 grade — 5 MPa', 'ISO 4427 / DIN 8074', 'SDR 7.4 to SDR 33', 'dn 16–400 mm', '100% virgin polyethylene'],
        featuresAr: ['درجة PE63 — 5 ميجاباسكال', 'معتمدة ISO 4427 / DIN 8074', 'SDR 7.4 إلى SDR 33', 'dn 16–400 مم', 'بولي إيثيلين خام 100%'],
        featuresFr: ['Grade PE63 — 5 MPa', 'Certifié ISO 4427 / DIN 8074', 'SDR 7.4 à SDR 33', 'dn 16–400 mm', 'Polyéthylène vierge 100 %'],
        image: '/images/products/cover/hdpe/pipes/CROWN PLASTIC HDPE PIPE PE63.png',
      },
      {
        slug: 'hdpe-pipes-6-3mpa-pe80',
        name: 'HDPE Pipes 6.3 MPa (PE80)',
        nameAr: 'أنابيب HDPE بضغط 6.3 ميجاباسكال (PE80)',
        nameFr: 'Tuyaux HDPE 6.3 MPa (PE80)',
        shortLabel: '6.3 MPa (PE80)',
        shortLabelAr: '6.3 MPa (PE80)',
        shortLabelFr: '6.3 MPa (PE80)',
        standards: ['PE80', '6.3 MPa'],
        shortDescription: 'HDPE pipes rated at 6.3 MPa (PE80 grade).',
        shortDescriptionAr: 'أنابيب HDPE بتصنيف 6.3 ميجاباسكال (درجة PE80).',
        shortDescriptionFr: 'Tuyaux HDPE classés 6.3 MPa (grade PE80).',
        features: ['PE80 grade — 6.3 MPa', 'ISO 4427 / DIN 8074', 'Water & gas networks', 'HDD trenchless compatible', '50-year service life'],
        featuresAr: ['درجة PE80 — 6.3 ميجاباسكال', 'معتمدة ISO 4427 / DIN 8074', 'شبكات مياه وغاز', 'متوافقة مع الحفر الأفقي HDD', 'عمر خدمة 50 عاماً'],
        featuresFr: ['Grade PE80 — 6.3 MPa', 'Certifié ISO 4427 / DIN 8074', 'Réseaux d\'eau et de gaz', 'Compatible forage horizontal HDD', 'Durée de vie 50 ans'],
        image: '/images/products/cover/hdpe/pipes/CROWN PLASTIC HDPE PIPE PE80.png',
      },
      {
        slug: 'hdpe-pipes-8mpa-pe100',
        name: 'HDPE Pipes 8 MPa (PE100)',
        nameAr: 'أنابيب HDPE بضغط 8 ميجاباسكال (PE100)',
        nameFr: 'Tuyaux HDPE 8 MPa (PE100)',
        shortLabel: '8 MPa (PE100)',
        shortLabelAr: '8 MPa (PE100)',
        shortLabelFr: '8 MPa (PE100)',
        standards: ['PE100', '8 MPa'],
        shortDescription: 'HDPE pipes rated at 8 MPa (PE100 grade).',
        shortDescriptionAr: 'أنابيب HDPE بتصنيف 8 ميجاباسكال (درجة PE100).',
        shortDescriptionFr: 'Tuyaux HDPE classés 8 MPa (grade PE100).',
        features: ['PE100 grade — 8 MPa', 'Highest design stress', 'SDR 11 to SDR 17', 'dn 32–400 mm', 'High-pressure gas & water'],
        featuresAr: ['درجة PE100 — 8 ميجاباسكال', 'أعلى إجهاد تصميم', 'SDR 11 إلى SDR 17', 'dn 32–400 مم', 'غاز ومياه ضغط عالي'],
        featuresFr: ['Grade PE100 — 8 MPa', 'Contrainte de conception maximale', 'SDR 11 à SDR 17', 'dn 32–400 mm', 'Gaz et eau haute pression'],
        image: '/images/products/cover/hdpe/pipes/CROWN PLASTIC HDPE PIPE PE100.png',
      },
      {
        slug: 'hdpe-pipes-din-8072',
        name: 'HDPE Pipes DIN 8072',
        nameAr: 'أنابيب HDPE وفق DIN 8072',
        nameFr: 'Tuyaux HDPE DIN 8072',
        shortLabel: 'DIN 8072',
        shortLabelAr: 'DIN 8072',
        shortLabelFr: 'DIN 8072',
        standards: ['DIN 8072'],
        shortDescription: 'HDPE pipes to DIN 8072 standard.',
        shortDescriptionAr: 'أنابيب HDPE وفق معيار DIN 8072.',
        shortDescriptionFr: 'Tuyaux HDPE selon norme DIN 8072.',
        features: ['DIN 8072 LLDPE', '2.5 to 10 bar', '10–110 mm', 'Agricultural irrigation', 'UAE manufactured'],
        featuresAr: ['معتمدة DIN 8072 LLDPE', '2.5 إلى 10 بار', '10–110 مم', 'الري الزراعي', 'مصنعة في الإمارات'],
        featuresFr: ['Certifié DIN 8072 LLDPE', '2,5 à 10 bar', '10–110 mm', 'Irrigation agricole', 'Fabriqué aux EAU'],
        image: '/images/products/cover/hdpe/pipes/CROWN PLASTIC HDPE PIPE DIN 8072.png',
      },
      {
        slug: 'hdpe-pipes-asae-s435',
        name: 'HDPE Pipes ASAE S435',
        nameAr: 'أنابيب HDPE وفق ASAE S435',
        nameFr: 'Tuyaux HDPE ASAE S435',
        shortLabel: 'ASAE S435',
        shortLabelAr: 'ASAE S435',
        shortLabelFr: 'ASAE S435',
        standards: ['ASAE S435'],
        shortDescription: 'HDPE pipes to ASAE S435 standard for agricultural applications.',
        shortDescriptionAr: 'أنابيب HDPE وفق معيار ASAE S435 للتطبيقات الزراعية.',
        shortDescriptionFr: 'Tuyaux HDPE selon norme ASAE S435 pour applications agricoles.',
        features: ['ASAE S435 certified', 'Drip tubing ½″–1″', 'Precision irrigation', 'Up to 4.8 bar', 'UAE agriculture'],
        featuresAr: ['معتمدة ASAE S435', 'أنابيب تنقيط ½″–1″', 'ري دقيق', 'حتى 4.8 بار', 'زراعة الإمارات'],
        featuresFr: ['Certifié ASAE S435', 'Tubes de goutte-à-goutte ½″–1″', 'Irrigation de précision', 'Jusqu\'à 4,8 bar', 'Agriculture EAU'],
        image: '/images/products/cover/hdpe/pipes/CROWN PLASTIC HDPE PIPE ASAE S435.png',
      },
      {
        slug: 'hdpe-pipes-aust-std-2698',
        name: 'HDPE Pipes AUST STD 2698-1: 1984',
        nameAr: 'أنابيب HDPE وفق المعيار الأسترالي 2698-1: 1984',
        nameFr: 'Tuyaux HDPE AUST STD 2698-1: 1984',
        shortLabel: 'AUST STD 2698-1',
        shortLabelAr: 'AUST STD 2698-1',
        shortLabelFr: 'AUST STD 2698-1',
        standards: ['AUST STD 2698-1:1984'],
        shortDescription: 'HDPE pipes to Australian Standard 2698-1:1984.',
        shortDescriptionAr: 'أنابيب HDPE وفق المعيار الأسترالي 2698-1:1984.',
        shortDescriptionFr: 'Tuyaux HDPE selon norme australienne 2698-1:1984.',
        features: ['AUST STD 2698-1:1984', '250 m coils', 'Drip irrigation', '3–4 bar working pressure', 'Large-scale farming'],
        featuresAr: ['المعيار الأسترالي 2698-1:1984', 'لفات 250 متر', 'ري بالتنقيط', 'ضغط تشغيل 3–4 بار', 'زراعة واسعة النطاق'],
        featuresFr: ['Norme australienne 2698-1:1984', 'Bobines de 250 m', 'Irrigation goutte-à-goutte', 'Pression de service 3–4 bar', 'Agriculture à grande échelle'],
        image: '/images/products/cover/hdpe/pipes/CROWN PLASTIC HDPE PIPE AUST STD 2698-11984.png',
      },
      {
        slug: 'hdpe-pipes-bs-1972-67',
        name: 'HDPE Pipes BS 1972/67',
        nameAr: 'أنابيب HDPE وفق BS 1972/67',
        nameFr: 'Tuyaux HDPE BS 1972/67',
        shortLabel: 'BS 1972/67',
        shortLabelAr: 'BS 1972/67',
        shortLabelFr: 'BS 1972/67',
        standards: ['BS 1972/67'],
        shortDescription: 'HDPE pipes to BS 1972/67 standard.',
        shortDescriptionAr: 'أنابيب HDPE وفق معيار BS 1972/67.',
        shortDescriptionFr: 'Tuyaux HDPE selon norme BS 1972/67.',
        features: ['BS 1972/67 LDPE', 'Class B, C, D', '⅔″–4″', 'Low-to-medium pressure', 'Irrigation & water'],
        featuresAr: ['معتمدة BS 1972/67 LDPE', 'فئة B و C و D', '⅔″–4″', 'ضغط منخفض إلى متوسط', 'ري ومياه'],
        featuresFr: ['Certifié BS 1972/67 LDPE', 'Classes B, C, D', '⅔″–4″', 'Basse à moyenne pression', 'Irrigation et eau'],
        image: '/images/products/cover/hdpe/pipes/CROWN PLASTIC HDPE PIPE BS 1972.png',
      },
      {
        slug: 'polyethylene-pipe-rolls',
        name: 'Polyethylene Pipe Rolls (Class C / HD)',
        nameAr: 'لفات أنابيب البولي إيثيلين (الفئة C / HD)',
        nameFr: 'Rouleaux de Tuyaux Polyéthylène (Classe C / HD)',
        shortLabel: 'Polyethylene Rolls',
        shortLabelAr: 'لفات بولي إيثيلين',
        shortLabelFr: 'Rouleaux Polyéthylène',
        standards: ['Class C', 'HD'],
        shortDescription: 'High-density polythene (HDPE) pipe rolls designed for flexible, long-distance agricultural, irrigation, and industrial fluid distribution.',
        shortDescriptionAr: 'لفات أنابيب بولي إيثيلين عالي الكثافة (HDPE) مصممة للتوزيع المرن للسوائل لمسافات طويلة في الزراعة والري والصناعة.',
        shortDescriptionFr: 'Rouleaux de tuyaux polyéthylène haute densité (HDPE) conçus pour la distribution flexible de fluides sur longues distances en agriculture, irrigation et industrie.',
        features: ['High flexibility for easy installation', 'Excellent resistance to environmental stress cracking', 'UV stabilized for outdoor deployment', 'Continuous lengths', 'Leak-free performance'],
        featuresAr: ['مرونة عالية لسهولة التركيب', 'مقاومة ممتازة للتشقق بسبب الإجهاد البيئي', 'مثبتة ضد الأشعة فوق البنفسجية للاستخدام الخارجي', 'أطوال مستمرة', 'أداء مانع للتسرب'],
        featuresFr: ['Haute flexibilité pour installation facile', 'Excellente résistance à la fissuration sous contrainte environnementale', 'Stabilisé UV pour déploiement extérieur', 'Longueurs continues', 'Performance sans fuite'],
        image: '/images/products/sub_products/HDPE.jpg',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 11) PEX PIPES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'pex-pipes',
    name: 'PEX Pipes',
    nameAr: 'أنابيب PEX',
    nameFr: 'Tuyaux PEX',
    shortDescription: 'DM-compliant cross-linked polyethylene Pipes / Fittings in PN 12.5 and PN 20, certified to DIN 16892/16893. Burst-tested to 30.0 MPa. Vicat softening at 133°C with derating factor 0.75 at 50°C ambient — continuous service to 95°C. Tolerance: ±0.2 mm. Certification ref: DM-PEX-PN20-2024-001.',
    shortDescriptionAr: 'أنابيب / تجهيزات بولي إيثيلين متشابك متوافقة مع بلدية دبي بتصنيفات PN 12.5 و PN 20 معتمدة وفق DIN 16892/16893. مختبرة بضغط انفجار 30.0 ميجاباسكال. تليين فيكات عند 133°C بمعامل تخفيض 0.75 عند حرارة محيطة 50°C — خدمة مستمرة حتى 95°C. التفاوت: ±0.2 مم. رقم الشهادة: DM-PEX-PN20-2024-001.',
    shortDescriptionFr: 'Tuyaux / Raccords en polyéthylène réticulé conformes Municipalité de Dubaï en PN 12.5 et PN 20, certifiés DIN 16892/16893. Testés en éclatement à 30,0 MPa. Ramollissement Vicat à 133 °C avec facteur de déclassement 0,75 à 50 °C ambiant — service continu jusqu\'à 95 °C. Tolérance : ±0,2 mm. Réf. certification : DM-PEX-PN20-2024-001.',
    icon: '🔴',
    image: '/images/products/cover/pex/pipes/pex.png',
    subProducts: [
      {
        slug: 'pex-pipes-pn-12-5-pn-20',
        name: 'PEX Pipes PN 12.5 & PN 20',
        nameAr: 'أنابيب PEX وفق PN 12.5 و PN 20',
        nameFr: 'Tuyaux PEX PN 12.5 & PN 20',
        shortLabel: 'PN 12.5 & PN 20',
        shortLabelAr: 'PN 12.5 و PN 20',
        shortLabelFr: 'PN 12.5 & PN 20',
        standards: ['PN 12.5', 'PN 20'],
        shortDescription: 'Cross-linked polyethylene (PEX) pipes rated at PN 12.5 and PN 20.',
        shortDescriptionAr: 'أنابيب البولي إيثيلين المتشابك (PEX) بتصنيف PN 12.5 و PN 20.',
        shortDescriptionFr: 'Tuyaux en polyéthylène réticulé (PEX) classés PN 12.5 et PN 20.',
        features: ['PN 12.5 & PN 20 rated', 'DIN 16892/16893 certified', 'Up to 95°C hot water', 'Underfloor heating specialist', '50-year service life'],
        featuresAr: ['مصنفة PN 12.5 و PN 20', 'معتمدة DIN 16892/16893', 'مياه ساخنة حتى 95°C', 'متخصصة بالتدفئة تحت الأرضية', 'عمر خدمة 50 عاماً'],
        featuresFr: ['Classement PN 12.5 & PN 20', 'Certifié DIN 16892/16893', 'Eau chaude jusqu\'à 95 °C', 'Spécialiste chauffage par le sol', 'Durée de vie 50 ans'],
        image: '/images/products/cover/pex/pipes/pex.png',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 12) FABRICATIONS & ACCESSORIES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'fabrications-accessories',
    name: 'Fabrications & Accessories',
    nameAr: 'التصنيعات والإكسسوارات',
    nameFr: 'Fabrications & Accessoires',
    shortDescription: 'Dubai Municipality-approved fabricated Pipes / Fittings: Grease Traps Types A–D and custom PVC/UPVC fabrications. Tolerance ±0.5 mm on custom builds. Thermal expansion coefficient 0.06 mm/m·K factored into all joint designs. Deployed 85 Type-A and Type-B grease traps for Dubai Food Court District — full DM compliance.',
    shortDescriptionAr: 'أنابيب / تجهيزات مصنعة معتمدة من بلدية دبي: مصائد الدهون أنواع A–D وتصنيعات PVC/UPVC مخصصة. تفاوت ±0.5 مم على التصنيعات المخصصة. معامل التمدد الحراري 0.06 مم/م·كلفن مدمج في جميع تصاميم الوصلات. تم توريد 85 مصيدة دهون من النوعين A و B لمنطقة فود كورت دبي — توافق كامل مع بلدية دبي.',
    shortDescriptionFr: 'Tuyaux / Raccords fabriqués sur mesure approuvés Municipalité de Dubaï : séparateurs de graisses Types A–D et fabrications PVC/UPVC personnalisées. Tolérance ±0,5 mm sur fabrications sur mesure. Coefficient de dilatation thermique 0,06 mm/m·K intégré dans toutes les conceptions de joints. 85 séparateurs de graisses Types A et B fournis pour le quartier Food Court de Dubaï — conformité totale Municipalité de Dubaï.',
    icon: '🏭',
    image: '/images/products/cover/fabrication/grease-trap-type-a.png',
    subProducts: [
      {
        slug: 'fabrication-grease-trap-type-a',
        name: 'PVC/UPVC Fabrication Grease Trap Type - A',
        nameAr: 'مصيدة الدهون PVC/UPVC النوع A',
        nameFr: 'Séparateur de Graisses PVC/UPVC Type A',
        shortLabel: 'Type A',
        shortLabelAr: 'النوع A',
        shortLabelFr: 'Type A',
        standards: ['Dubai Municipality Approved', 'ISO 9001:2015'],
        shortDescription: 'Single bucket grease trap (450mm deep) with GRP sealed cover.',
        shortDescriptionAr: 'مصيدة دهون بدلو واحد (عمق 450 مم) مع غطاء GRP محكم.',
        shortDescriptionFr: 'Séparateur de graisses à bac unique (profondeur 450 mm) avec couvercle GRP étanche.',
        features: ['Custom build to site specs', 'Dubai Municipality approved', '450mm deep PVC bucket', 'GRP sealed cover', 'Neoprene gasket seal'],
        featuresAr: ['تصنيع حسب مواصفات الموقع', 'معتمدة من بلدية دبي', 'دلو PVC بعمق 450 مم', 'غطاء GRP محكم', 'حشية نيوبرين'],
        featuresFr: ['Fabrication sur mesure selon spécifications du site', 'Approuvé Municipalité de Dubaï', 'Bac PVC profondeur 450 mm', 'Couvercle GRP étanche', 'Joint néoprène'],
        image: '/images/products/cover/fabrication/grease-trap-type-a.png',
      },
      {
        slug: 'fabrication-grease-trap-type-b',
        name: 'PVC/UPVC Fabrication Grease Trap Type - B',
        nameAr: 'مصيدة الدهون PVC/UPVC النوع B',
        nameFr: 'Séparateur de Graisses PVC/UPVC Type B',
        shortLabel: 'Type B',
        shortLabelAr: 'النوع B',
        shortLabelFr: 'Type B',
        standards: ['Dubai Municipality Approved', 'ISO 9001:2015'],
        shortDescription: 'Dual bucket grease trap (260mm deep each) with lifting handles.',
        shortDescriptionAr: 'مصيدة دهون بدلوين (عمق 260 مم لكل منهما) مع مقابض رفع.',
        shortDescriptionFr: 'Séparateur de graisses à double bac (profondeur 260 mm chacun) avec poignées de levage.',
        features: ['Twin bucket design', 'Dubai Municipality approved', '260mm deep each', '3-unit GRP cover', 'High-capacity kitchen use'],
        featuresAr: ['تصميم دلو مزدوج', 'معتمدة من بلدية دبي', 'عمق 260 مم لكل منهما', 'غطاء GRP من 3 قطع', 'استخدام مطابخ عالية السعة'],
        featuresFr: ['Conception à double bac', 'Approuvé Municipalité de Dubaï', 'Profondeur 260 mm chacun', 'Couvercle GRP 3 pièces', 'Usage cuisines à haute capacité'],
        image: '/images/products/cover/fabrication/grease-trap-type-b.png',
      },
      {
        slug: 'fabrication-grease-trap-type-c',
        name: 'PVC/UPVC Fabrication Grease Trap Type - C',
        nameAr: 'مصيدة الدهون PVC/UPVC النوع C',
        nameFr: 'Séparateur de Graisses PVC/UPVC Type C',
        shortLabel: 'Type C',
        shortLabelAr: 'النوع C',
        shortLabelFr: 'Type C',
        standards: ['Dubai Municipality Approved', 'ISO 9001:2015'],
        shortDescription: 'Large baffle grease trap (1980mm length) for high-capacity applications.',
        shortDescriptionAr: 'مصيدة دهون كبيرة بحواجز (طول 1980 مم) لتطبيقات السعة العالية.',
        shortDescriptionFr: 'Séparateur de graisses à cloisons grande capacité (longueur 1980 mm) pour applications à haut débit.',
        features: ['Large-capacity baffle', 'Dubai Municipality approved', '5-row perforated bucket', 'Neoprene sealed', 'Industrial MEP projects'],
        featuresAr: ['حاجز كبير السعة', 'معتمدة من بلدية دبي', 'دلو مثقب 5 صفوف', 'محكمة بالنيوبرين', 'مشاريع MEP صناعية'],
        featuresFr: ['Cloison grande capacité', 'Approuvé Municipalité de Dubaï', 'Bac perforé 5 rangées', 'Étanchéité néoprène', 'Projets MEP industriels'],
        image: '/images/products/cover/fabrication/grease-trap-type-c.png',
      },
      {
        slug: 'fabrication-grease-trap-type-d',
        name: 'PVC/UPVC Fabrication Grease Trap Type - D',
        nameAr: 'مصيدة الدهون PVC/UPVC النوع D',
        nameFr: 'Séparateur de Graisses PVC/UPVC Type D',
        shortLabel: 'Type D',
        shortLabelAr: 'النوع D',
        shortLabelFr: 'Type D',
        standards: ['Dubai Municipality Approved', 'ISO 9001:2015'],
        shortDescription: 'Compact grease trap with GRP cover secured by 24 wing nuts.',
        shortDescriptionAr: 'مصيدة دهون مدمجة مع غطاء GRP مثبت بـ 24 صامولة فراشية.',
        shortDescriptionFr: 'Séparateur de graisses compact avec couvercle GRP fixé par 24 écrous papillon.',
        features: ['Compact design', 'Dubai Municipality approved', '2″ PVC waste inlet', '600×450mm PVC cover', '24 wing nut secured'],
        featuresAr: ['تصميم مدمج', 'معتمدة من بلدية دبي', 'مدخل مخلفات PVC 2″', 'غطاء PVC بمقاس 600×450 مم', 'مثبت بـ 24 صامولة فراشية'],
        featuresFr: ['Conception compacte', 'Approuvé Municipalité de Dubaï', 'Entrée déchets PVC 2″', 'Couvercle PVC 600×450 mm', 'Fixation par 24 écrous papillon'],
        image: '/images/products/cover/fabrication/grease-trap-type-d.png',
      },
      {
        slug: 'fabrication-accessories',
        name: 'PVC/UPVC Fabrication Accessories',
        nameAr: 'إكسسوارات التصنيع PVC/UPVC',
        nameFr: 'Accessoires de Fabrication PVC/UPVC',
        shortLabel: 'Accessories',
        shortLabelAr: 'الإكسسوارات',
        shortLabelFr: 'Accessoires',
        standards: ['Crown Specification'],
        shortDescription: 'Custom PVC/UPVC fabrication accessories for specialized projects.',
        shortDescriptionAr: 'إكسسوارات تصنيع PVC/UPVC مخصصة للمشاريع المتخصصة.',
        shortDescriptionFr: 'Accessoires de fabrication PVC/UPVC personnalisés pour projets spécialisés.',
        features: ['Duct caps & sockets', 'Bellmouths & LR bends', 'Brass hardware', 'Custom fabrication', 'UAE telecom & electrical'],
        featuresAr: ['أغطية ووصلات قنوات', 'فتحات جرس وانحناءات', 'عتاد نحاسي', 'تصنيع مخصص', 'اتصالات وكهرباء الإمارات'],
        featuresFr: ['Bouchons et manchons de gaines', 'Évases et coudes', 'Quincaillerie laiton', 'Fabrication sur mesure', 'Télécom et électricité EAU'],
        image: '/images/fabrications/fabrications-cover-composite.jpg',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 13) SOLVENTS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: 'solvents',
    name: 'Solvents',
    nameAr: 'المذيبات',
    nameFr: 'Solvants',
    shortDescription: 'PVC solvent cements formulated for Gulf-climate pipe jointing. Accelerated cure chemistry calibrated for 35°C–50°C ambient application windows. Compatible with all Crown Pipes / Fittings across BS EN 1452, DIN 8063, and ASTM D 2466 systems.',
    shortDescriptionAr: 'أسمنت مذيب PVC مصمم لوصل الأنابيب في مناخ الخليج. كيمياء معالجة مسرّعة معايرة لنوافذ تطبيق 35°C–50°C. متوافق مع جميع أنابيب / تجهيزات كراون عبر أنظمة BS EN 1452 و DIN 8063 و ASTM D 2466.',
    shortDescriptionFr: 'Colles solvants PVC formulées pour l\'assemblage de tuyaux en climat du Golfe. Chimie de polymérisation accélérée calibrée pour des fenêtres d\'application de 35 °C–50 °C. Compatible avec tous les Tuyaux / Raccords Crown sur systèmes BS EN 1452, DIN 8063 et ASTM D 2466.',
    icon: '🧴',
    image: '/images/products/sub_products/PVC.jpg',
    subProducts: [
      {
        slug: 'pvc-solvents',
        name: 'PVC Solvents',
        nameAr: 'مذيبات PVC',
        nameFr: 'Solvants PVC',
        shortLabel: 'PVC Solvents',
        shortLabelAr: 'مذيبات PVC',
        shortLabelFr: 'Solvants PVC',
        standards: ['Crown Specification'],
        shortDescription: 'PVC solvent cements for secure and durable pipe joints.',
        shortDescriptionAr: 'أسمنت مذيب PVC للوصلات الآمنة والمتينة.',
        shortDescriptionFr: 'Colles solvants PVC pour assemblages sûrs et durables.',
        features: [],
        featuresAr: [],
        image: '/images/products/cover/solvent/Solventcover.png',
      },
    ],
  },
];

// Helper function to get category by slug
export function getCategoryBySlug(slug: string): ProductCategory | undefined {
  return productCategories.find((cat) => cat.slug === slug);
}

// Helper function to get sub-product by slugs
export function getSubProductBySlugs(categorySlug: string, productSlug: string): SubProduct | undefined {
  const category = getCategoryBySlug(categorySlug);
  return category?.subProducts.find((p) => p.slug === productSlug);
}

// Helper to get all products flat
export function getAllProducts(): { category: ProductCategory; product: SubProduct }[] {
  return productCategories.flatMap((category) =>
    category.subProducts.map((product) => ({ category, product }))
  );
}
