const fs = require('fs');
const path = require('path');
const dir = 'src/config/productDetails';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.ts') && f !== 'index.ts' && f !== 'bsEn1452SpecTables.ts');
const labels = new Set();
const groupLabels = new Set();
const superGroupLabels = new Set();
const megaGroupLabels = new Set();
let faqCount = 0;
files.forEach(file => {
  const content = fs.readFileSync(path.join(dir, file), 'utf8');
  // label: 'xxx' or label: `xxx`
  let m;
  const re1 = /label\s*:\s*['`]([^'`\n]+)['`]/g;
  while ((m = re1.exec(content)) !== null) labels.add(m[1]);
  const re2 = /groupLabel\s*:\s*['`]([^'`\n]+)['`]/g;
  while ((m = re2.exec(content)) !== null) groupLabels.add(m[1]);
  const re3 = /superGroupLabel\s*:\s*['`]([^'`\n]+)['`]/g;
  while ((m = re3.exec(content)) !== null) superGroupLabels.add(m[1]);
  const re4 = /megaGroupLabel\s*:\s*['`]([^'`\n]+)['`]/g;
  while ((m = re4.exec(content)) !== null) megaGroupLabels.add(m[1]);
  const faqMatches = content.match(/qAr\s*:/g);
  if (faqMatches) faqCount += faqMatches.length;
});
console.log('=== UNIQUE LABELS ===');
[...labels].sort().forEach(l => console.log('  ' + JSON.stringify(l)));
console.log('\n=== UNIQUE GROUP LABELS ===');
[...groupLabels].sort().forEach(l => console.log('  ' + JSON.stringify(l)));
console.log('\n=== UNIQUE SUPER GROUP LABELS ===');
[...superGroupLabels].sort().forEach(l => console.log('  ' + JSON.stringify(l)));
console.log('\n=== UNIQUE MEGA GROUP LABELS ===');
[...megaGroupLabels].sort().forEach(l => console.log('  ' + JSON.stringify(l)));
console.log('\nFAQ entries found: ' + faqCount);
console.log('Total unique labels: ' + labels.size);
console.log('Total unique groupLabels: ' + groupLabels.size);
